return {
  ['.notdef'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['alefmapiq'] = { 0xFB30 },-- HEBREW LETTER ALEF WITH MAPIQ
  ['circledash'] = { 0x25CC },-- DOTTED CIRCLE
  ['circledashdagesh'] = { 0x25CC, 0x05BC },-- DOTTED CIRCLE/HEBREW POINT DAGESH OR MAPIQ
  ['endofword'] = { 0x2060 },-- WORD JOINER
  ['hatafpatah1'] = { 0x05B2 },-- HEBREW POINT HATAF PATAH
  ['hatafpatah2'] = { 0x05B2 },-- HEBREW POINT HATAF PATAH
  ['hatafqamats1'] = { 0x05B3 },-- HEBREW POINT HATAF QAMATS
  ['hatafqamats2'] = { 0x05B3 },-- HEBREW POINT HATAF QAMATS
  ['hatafsegol1'] = { 0x05B1 },-- HEBREW POINT HATAF SEGOL
  ['hatafsegol2'] = { 0x05B1 },-- HEBREW POINT HATAF SEGOL
  ['hiriq1'] = { 0x05B4 },-- HEBREW POINT HIRIQ
  ['hiriq2'] = { 0x05B4 },-- HEBREW POINT HIRIQ
  ['hiriq3'] = { 0x05B4 },-- HEBREW POINT HIRIQ
  ['holam1'] = { 0x05B9 },-- HEBREW POINT HOLAM
  ['holam2'] = { 0x05B9 },-- HEBREW POINT HOLAM
  ['kaffinal'] = { 0x05DA },-- HEBREW LETTER FINAL KAF
  ['kaffinaldagesh'] = { 0xFB3A },-- HEBREW LETTER FINAL KAF WITH DAGESH
  ['kaffinalqamats'] = { 0x05DA, 0x05B8 },-- HEBREW LETTER FINAL KAF/HEBREW POINT QAMATS
  ['kaffinalsheva'] = { 0x05DA, 0x05B0 },-- HEBREW LETTER FINAL KAF/HEBREW POINT SHEVA
  ['kafqamats'] = { 0x05DB, 0x05B8 },-- HEBREW LETTER KAF/HEBREW POINT QAMATS
  ['kafsheva'] = { 0x05DB, 0x05B0 },-- HEBREW LETTER KAF/HEBREW POINT SHEVA
  ['maqaf'] = { 0x05BE },-- HEBREW PUNCTUATION MAQAF
  ['memfinal'] = { 0x05DD },-- HEBREW LETTER FINAL MEM
  ['nunfinal'] = { 0x05DF },-- HEBREW LETTER FINAL NUN
  ['nunfinalqamats'] = { 0x05DF, 0x05B8 },-- HEBREW LETTER FINAL NUN/HEBREW POINT QAMATS
  ['nunqamats'] = { 0x05E0, 0x05B8 },-- HEBREW LETTER NUN/HEBREW POINT QAMATS
  ['patah1'] = { 0x05B7 },-- HEBREW POINT PATAH
  ['patah2'] = { 0x05B7 },-- HEBREW POINT PATAH
  ['patah3'] = { 0x05B7 },-- HEBREW POINT PATAH
  ['patahfurtivum'] = { 0x05B7 },-- HEBREW POINT PATAH
  ['pefinal'] = { 0x05E3 },-- HEBREW LETTER FINAL PE
  ['pefinaldagesh'] = { 0xFB43 },-- HEBREW LETTER FINAL PE WITH DAGESH
  ['qamats1'] = { 0x05B8 },-- HEBREW POINT QAMATS
  ['qamats2'] = { 0x05B8 },-- HEBREW POINT QAMATS
  ['qamats3'] = { 0x05B8 },-- HEBREW POINT QAMATS
  ['qibuts'] = { 0x05BB },-- HEBREW POINT QUBUTS
  ['qibuts1'] = { 0x05BB },-- HEBREW POINT QUBUTS
  ['qibuts2'] = { 0x05BB },-- HEBREW POINT QUBUTS
  ['qibuts3'] = { 0x05BB },-- HEBREW POINT QUBUTS
  ['reshdagesh'] = { 0xFB48 },-- HEBREW LETTER RESH WITH DAGESH
  ['segol1'] = { 0x05B6 },-- HEBREW POINT SEGOL
  ['segol2'] = { 0x05B6 },-- HEBREW POINT SEGOL
  ['segol3'] = { 0x05B6 },-- HEBREW POINT SEGOL
  ['sheva1'] = { 0x05B0 },-- HEBREW POINT SHEVA
  ['sheva2'] = { 0x05B0 },-- HEBREW POINT SHEVA
  ['sheva3'] = { 0x05B0 },-- HEBREW POINT SHEVA
  ['shindot'] = { 0x05C1 },-- HEBREW POINT SHIN DOT
  ['shinshindotdagesh'] = { 0xFB2C },-- HEBREW LETTER SHIN WITH DAGESH AND SHIN DOT
  ['shinsindotdagesh'] = { 0xFB2D },-- HEBREW LETTER SHIN WITH DAGESH AND SIN DOT
  ['sindot'] = { 0x05C2 },-- HEBREW POINT SIN DOT
  ['sofpasuq'] = { 0x05C3 },-- HEBREW PUNCTUATION SOF PASUQ
  ['tsadifinal'] = { 0x05E5 },-- HEBREW LETTER FINAL TSADI
  ['tsere1'] = { 0x05B5 },-- HEBREW POINT TSERE
  ['tsere2'] = { 0x05B5 },-- HEBREW POINT TSERE
  ['tsere3'] = { 0x05B5 },-- HEBREW POINT TSERE
  ['zeronojoin'] = { 0x200C },-- ZERO WIDTH NON-JOINER
  }
