return {
  ['.notdef'] = { 0x0020 },-- SPACE
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['Delta'] = { 0x1D6AB, },-- MATHEMATICAL BOLD CAPITAL DELTA
  ['Phi'] = { 0x1D6BD, },-- MATHEMATICAL BOLD CAPITAL PHI
  ['Gamma'] = { 0x1D6AA, },-- MATHEMATICAL BOLD CAPITAL GAMMA
  ['Lambda'] = { 0x1D6B2, },-- MATHEMATICAL BOLD CAPITAL LAMDA
  ['Pi'] = { 0x1D6B7, },-- MATHEMATICAL BOLD CAPITAL PI
  ['Theta'] = { 0x1D6AF, },-- MATHEMATICAL BOLD CAPITAL THETA
  ['Sigma'] = { 0x1D6BA, },-- MATHEMATICAL BOLD CAPITAL SIGMA
  ['Upsilon'] = { 0x1D6BC, },-- MATHEMATICAL BOLD CAPITAL UPSILON
  ['Omega'] = { 0x1D6C0, },-- MATHEMATICAL BOLD CAPITAL OMEGA
  ['Xi'] = { 0x1D6B5, },-- MATHEMATICAL BOLD CAPITAL XI
  ['Psi'] = { 0x1D6BF, },-- MATHEMATICAL BOLD CAPITAL PSI
}
