return {
  ['Acute'] = { 0x00B4 },-- ACUTE ACCENT
  ['Acutecomb'] = { 0x0301 },-- COMBINING ACUTE ACCENT
  ['anglearc'] = { 0x2222 },-- SPHERICAL ANGLE
  ['Aogonekacute'] = { 0x00C1, 0x0328 },-- LATIN CAPITAL LETTER A WITH ACUTE/COMBINING OGONEK
  ['aogonekacute'] = { 0x0105, 0x0301 },-- LATIN SMALL LETTER A WITH OGONEK/COMBINING ACUTE ACCENT
  ['baht'] = { 0x0E3F },-- THAI CURRENCY SYMBOL BAHT
  ['bigcircle'] = { 0x25EF },-- LARGE CIRCLE
  ['blanksymbol'] = { 0x2422 },-- BLANK SYMBOL
  ['born'] = { 0x1F7C9 },-- LIGHT FIVE POINTED BLACK STAR
  ['Breve'] = { 0x02D8 },-- BREVE
  ['Breveacute'] = { 0x02D8, 0x0301 },-- BREVE/COMBINING ACUTE ACCENT
  ['breveacute'] = { 0x02D8, 0x0301 },-- BREVE/COMBINING ACUTE ACCENT
  ['brevebelow'] = { 0x032E },-- COMBINING BREVE BELOW
  ['brevebelowcomb'] = { 0x032E },-- COMBINING BREVE BELOW
  ['brevebelowinverted'] = { 0x032F },-- COMBINING INVERTED BREVE BELOW
  ['brevebelowinvertedcomb'] = { 0x032F },-- COMBINING INVERTED BREVE BELOW
  ['Brevecomb'] = { 0x0306 },-- COMBINING BREVE
  ['brevecomb'] = { 0x0306 },-- COMBINING BREVE
  ['Brevegrave'] = { 0x02D8, 0x0300 },-- BREVE/COMBINING GRAVE ACCENT
  ['brevegrave'] = { 0x02D8, 0x0300 },-- BREVE/COMBINING GRAVE ACCENT
  ['Brevehookabove'] = { 0x02D8, 0x0309 },-- BREVE/COMBINING HOOK ABOVE
  ['brevehookabove'] = { 0x02D8, 0x0309 },-- BREVE/COMBINING HOOK ABOVE
  ['Breveinverted'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['breveinverted'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['Breveinvertedcomb'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['breveinvertedcomb'] = { 0x0311 },-- COMBINING INVERTED BREVE
  ['Brevetilde'] = { 0x02D8, 0x0303 },-- BREVE/COMBINING TILDE
  ['brevetilde'] = { 0x02D8, 0x0303 },-- BREVE/COMBINING TILDE
  ['Caron'] = { 0x02C7 },-- CARON
  ['Caroncomb'] = { 0x030C },-- COMBINING CARON
  ['caroncomb'] = { 0x030C },-- COMBINING CARON
  ['Circumflex'] = { 0x02C6 },-- MODIFIER LETTER CIRCUMFLEX ACCENT
  ['Circumflexacute'] = { 0x02C6, 0x0301 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['circumflexacute'] = { 0x02C6, 0x0301 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['Circumflexcomb'] = { 0x0302 },-- COMBINING CIRCUMFLEX ACCENT
  ['circumflexcomb'] = { 0x0302 },-- COMBINING CIRCUMFLEX ACCENT
  ['Circumflexgrave'] = { 0x02C6, 0x0300 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['circumflexgrave'] = { 0x02C6, 0x0300 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['Circumflexhookabove'] = { 0x02C6, 0x0309 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['circumflexhookabove'] = { 0x02C6, 0x0309 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['Circumflextilde'] = { 0x02C6, 0x0303 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING TILDE
  ['circumflextilde'] = { 0x02C6, 0x0303 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/COMBINING TILDE
  ['commaaccent'] = { 0x0313 },-- COMBINING COMMA ABOVE
  ['commaaccentcomb'] = { 0x0313 },-- COMBINING COMMA ABOVE
  ['copyleft'] = { 0x1F12F },-- COPYLEFT SYMBOL
  ['cwmascender'] = { 0x200C },-- ZERO WIDTH NON-JOINER
  ['cwmcapital'] = { 0x200C },-- ZERO WIDTH NON-JOINER
  ['dblGrave'] = { 0x02F5 },-- MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT
  ['dblgrave'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['dblGravecomb'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['dblgravecomb'] = { 0x030F },-- COMBINING DOUBLE GRAVE ACCENT
  ['diameter'] = { 0x2300 },-- DIAMETER SIGN
  ['died'] = { 0x271D },-- LATIN CROSS
  ['Dieresis'] = { 0x00A8 },-- DIAERESIS
  ['Dieresisacute'] = { 0x00A8, 0x0301 },-- DIAERESIS/COMBINING ACUTE ACCENT
  ['dieresisacute'] = { 0x00A8, 0x0301 },-- DIAERESIS/COMBINING ACUTE ACCENT
  ['Dieresiscaron'] = { 0x00A8, 0x030C },-- DIAERESIS/COMBINING CARON
  ['dieresiscaron'] = { 0x00A8, 0x030C },-- DIAERESIS/COMBINING CARON
  ['Dieresiscomb'] = { 0x0308 },-- COMBINING DIAERESIS
  ['dieresiscomb'] = { 0x0308 },-- COMBINING DIAERESIS
  ['Dieresisgrave'] = { 0x00A8, 0x0300 },-- DIAERESIS/COMBINING GRAVE ACCENT
  ['dieresisgrave'] = { 0x00A8, 0x0300 },-- DIAERESIS/COMBINING GRAVE ACCENT
  ['discount'] = { 0x2052 },-- COMMERCIAL MINUS SIGN
  ['divorced'] = { 0x26AE },-- DIVORCE SYMBOL
  ['Dotaccent'] = { 0x02D9 },-- DOT ABOVE
  ['Dotaccentcomb'] = { 0x0307 },-- COMBINING DOT ABOVE
  ['dotaccentcomb'] = { 0x0307 },-- COMBINING DOT ABOVE
  ['dotbelow'] = { 0x0323 },-- COMBINING DOT BELOW
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['Eogonekacute'] = { 0x00C9, 0x0328 },-- LATIN CAPITAL LETTER E WITH ACUTE/COMBINING OGONEK
  ['eogonekacute'] = { 0x0119, 0x0301 },-- LATIN SMALL LETTER E WITH OGONEK/COMBINING ACUTE ACCENT
  ['gnaborretni'] = { 0x2E18 },-- INVERTED INTERROBANG
  ['Germandbls'] = { 0x0053, 0x0053 },-- LATIN CAPITAL LETTER S/LATIN CAPITAL LETTER S
  ['Grave'] = { 0x0060 },-- GRAVE ACCENT
  ['Gravecomb'] = { 0x0300 },-- COMBINING GRAVE ACCENT
  ['guarani'] = { 0x20B2 },-- GUARANI SIGN
  ['Hookabove'] = { 0x0309 },-- COMBINING HOOK ABOVE
  ['hookabove'] = { 0x0309 },-- COMBINING HOOK ABOVE
  ['Hookabovecomb'] = { 0x0309 },-- COMBINING HOOK ABOVE
  ['Htilde'] = { 0x0048, 0x0303 },-- LATIN CAPITAL LETTER H/COMBINING TILDE
  ['htilde'] = { 0x0068, 0x0303 },-- LATIN SMALL LETTER H/COMBINING TILDE
  ['Hungarumlaut'] = { 0x02DD },-- DOUBLE ACUTE ACCENT
  ['Hungarumlautcomb'] = { 0x030B },-- COMBINING DOUBLE ACUTE ACCENT
  ['hungarumlautcomb'] = { 0x030B },-- COMBINING DOUBLE ACUTE ACCENT
  ['hyphendbl'] = { 0x2E40 },-- DOUBLE HYPHEN
  ['hyphendbl.alt'] = { 0x2E40 },-- DOUBLE HYPHEN
  ['Iogonekacute'] = { 0x00CD, 0x0328 },-- LATIN CAPITAL LETTER I WITH ACUTE/COMBINING OGONEK
  ['iogonekacute'] = { 0x00ED, 0x0328 },-- LATIN SMALL LETTER I WITH ACUTE/COMBINING OGONEK
  ['Jacute'] = { 0x004A, 0x0301 },-- LATIN CAPITAL LETTER J/COMBINING ACUTE ACCENT
  ['jacute'] = { 0x0237, 0x0301 },-- LATIN SMALL LETTER DOTLESS J/COMBINING ACUTE ACCENT
  ['J_caron'] = { 0x004A, 0x0315 },-- LATIN CAPITAL LETTER J/COMBINING COMMA ABOVE RIGHT
  ['leaf'] = { 0x1F342 },-- FALLEN LEAF
  ['linebelow'] = { 0x005F },-- LOW LINE
  ['linebelowcomb'] = { 0x0332 },-- COMBINING LOW LINE
  ['Ltilde'] = { 0x004C, 0x0303 },-- LATIN CAPITAL LETTER L/COMBINING TILDE
  ['ltilde'] = { 0x006C, 0x0303 },-- LATIN SMALL LETTER L/COMBINING TILDE
  ['Macron'] = { 0x00AF },-- MACRON
  ['macronbelow'] = { 0x0331 },-- COMBINING MACRON BELOW
  ['macronbelowcomb'] = { 0x0331 },-- COMBINING MACRON BELOW
  ['Macroncomb'] = { 0x0304 },-- COMBINING MACRON
  ['macroncomb'] = { 0x0304 },-- COMBINING MACRON
  ['married'] = { 0x26AD },-- MARRIAGE SYMBOL
  ['mho'] = { 0x2127 },-- INVERTED OHM SIGN
  ['naira'] = { 0x20A6 },-- NAIRA SIGN
  ['ohm'] = { 0x2126 },-- OHM SIGN
  ['one.superior'] = { 0x00B9 },-- SUPERSCRIPT ONE
  ['Oogonekacute'] = { 0x01EA, 0x0301 },-- LATIN CAPITAL LETTER O WITH OGONEK/COMBINING ACUTE ACCENT
  ['oogonekacute'] = { 0x01EB, 0x0301 },-- LATIN SMALL LETTER O WITH OGONEK/COMBINING ACUTE ACCENT
  ['Orogate'] = { 0xA7C0 },-- LATIN CAPITAL LETTER OLD POLISH O
  ['orogate'] = { 0xA7C1 },-- LATIN SMALL LETTER OLD POLISH O
  ['permyriad'] = { 0x2031 },-- PER TEN THOUSAND SIGN
  ['perthousandzero'] = { 0x2080 },-- SUBSCRIPT ZERO
  ['peso'] = { 0xA750 },-- LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
  ['published'] = { 0x2117 },-- SOUND RECORDING COPYRIGHT
  ['quillbracketleft'] = { 0x2045 },-- LEFT SQUARE BRACKET WITH QUILL
  ['quillbracketright'] = { 0x2046 },-- RIGHT SQUARE BRACKET WITH QUILL
  ['recipe'] = { 0xA776 },-- LATIN LETTER SMALL CAPITAL RUM
  ['Ring'] = { 0x02DA },-- RING ABOVE
  ['Ringcomb'] = { 0x030A },-- COMBINING RING ABOVE
  ['ringcomb'] = { 0x030A },-- COMBINING RING ABOVE
  ['Ringacute'] = { 0x02DA, 0x0301 },-- RING ABOVE/COMBINING ACUTE ACCENT
  ['ringacute'] = { 0x02DA, 0x0301 },-- RING ABOVE/COMBINING ACUTE ACCENT
  ['servicemark'] = { 0x2120 },-- SERVICE MARK
  ['Tcommaaccent'] = { 0x021A },-- LATIN CAPITAL LETTER T WITH COMMA BELOW
  ['tcommaaccent'] = { 0x021B},-- LATIN SMALL LETTER T WITH COMMA BELOW
  ['Ttilde'] = { 0x0054, 0x0303 },-- LATIN CAPITAL LETTER T/COMBINING TILDE
  ['ttilde'] = { 0x0074, 0x0303 },-- LATIN SMALL LETTER T/COMBINING TILDE
  ['Tdieresis'] = { 0x0054, 0x0308 },-- LATIN CAPITAL LETTER T/COMBINING DIAERESIS
  ['three.superior'] = { 0x00B3 },-- SUPERSCRIPT THREE
  ['threequartersemdash'] = { 0x2014 },-- EM DASH
  ['tieaccentcapital'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentcapital.new'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentlowercase'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentlowercase.new'] = { 0x2040 },-- CHARACTER TIE
  ['Tilde'] = { 0x02DC },-- SMALL TILDE
  ['tildebelow'] = { 0x0330 },-- COMBINING TILDE BELOW
  ['tildebelowcomb'] = { 0x0330 },-- COMBINING TILDE BELOW
  ['tildelow'] = { 0xFF5E },-- FULLWIDTH TILDE
  ['Tildecomb'] = { 0x0303 },-- COMBINING TILDE
  ['twelveudash'] = { 0xFE58 },-- SMALL EM DASH
  ['two.superior'] = { 0x00B2 },-- SUPERSCRIPT TWO
  ['Ubrevebelowinverted'] = { 0x0055, 0x032F },-- LATIN CAPITAL LETTER U/COMBINING INVERTED BREVE BELOW
  ['ubrevebelowinverted'] = { 0x0075, 0x032F },-- LATIN SMALL LETTER U/COMBINING INVERTED BREVE BELOW
  ['undertie'] = { 0x203F },-- UNDERTIE
  ['undertieinverted'] = { 0x2054 },-- INVERTED UNDERTIE
  ['varcopyright'] = { 0x00A9 },-- COPYRIGHT SIGN
  ['vardotaccent'] = { 0x02D9 },-- DOT ABOVE
  ['varregistered'] = { 0x00AE },-- REGISTERED SIGN
  }
