return {
  ['shortleftarrow'] = { 0x2190 },-- LEFTWARDS ARROW
  ['shortrightarrow'] = { 0x2192 },-- RIGHTWARDS ARROW
  ['shortuparrow'] = { 0x2191 },-- UPWARDS ARROW
  ['shortdownarrow'] = { 0x2193 },-- DOWNWARDS ARROW
  ['Yup'] = { 0x2144 },-- TURNED SANS-SERIF CAPITAL Y
  ['Ydown'] = { 0x1D5B8 },-- MATHEMATICAL SANS-SERIF CAPITAL Y
  ['Yleft'] = { 0x2919 },-- LEFTWARDS ARROW-TAIL
  ['Yright'] = { 0x291A },-- RIGHTWARDS ARROW-TAIL
  ['varcurlyvee'] = { 0x22CE, 0xFE01 },-- CURLY LOGICAL OR/VARIATION SELECTOR-2
  ['varcurlywedge'] = { 0x22CF, 0xFE01 },-- CURLY LOGICAL AND/VARIATION SELECTOR-2
  ['minuso'] = { 0x29B5 },-- CIRCLE WITH HORIZONTAL BAR
  ['baro'] = { 0x233D },-- APL FUNCTIONAL SYMBOL CIRCLE STILE
  ['sslash'] = { 0x2AFD },-- DOUBLE SOLIDUS OPERATOR
  ['bbslash'] = { 0x244A },-- OCR DOUBLE BACKSLASH
  ['moo'] = { 0x297F, 0x0336 },-- DOWN FISH TAIL/COMBINING LONG STROKE OVERLAY
  ['varotimes'] = { 0x2297 },-- CIRCLED TIMES
  ['varoast'] = { 0x229B },-- CIRCLED ASTERISK OPERATOR
  ['varobar'] = { 0x29B6 },-- CIRCLED VERTICAL BAR
  ['varodot'] = { 0x2299 },-- CIRCLED DOT OPERATOR
  ['varoslash'] = { 0x2298 },-- CIRCLED DIVISION SLASH
  ['varobslash'] = { 0x29B8 },-- CIRCLED REVERSE SOLIDUS
  ['varocircle'] = { 0x229A },-- CIRCLED RING OPERATOR
  ['varoplus'] = { 0x2295 },-- CIRCLED PLUS
  ['varominus'] = { 0x2296 },-- CIRCLED MINUS
  ['boxast'] = { 0x29C6 },-- SQUARED ASTERISK
  ['boxbar'] = { 0x25EB },-- WHITE SQUARE WITH VERTICAL BISECTING LINE
  ['boxdot'] = { 0x22A1 },-- SQUARED DOT OPERATOR
  ['boxslash'] = { 0x29C4 },-- SQUARED RISING DIAGONAL SLASH
  ['boxbslash'] = { 0x29C5 },-- SQUARED FALLING DIAGONAL SLASH
  ['boxcircle'] = { 0x29C7 },-- SQUARED SMALL CIRCLE
  ['boxbox'] = { 0x29C8 },-- SQUARED SQUARE
  ['boxempty'] = { 0x25A1 },-- WHITE SQUARE
  ['lightning'] = { 0x21AF },-- DOWNWARDS ZIGZAG ARROW
  ['merge'] = { 0x2A55 },-- TWO INTERSECTING LOGICAL AND
  ['vartimes'] = { 0x2A09 },-- N-ARY TIMES OPERATOR
  ['fatsemi'] = { 0x2A3E },-- Z NOTATION RELATIONAL COMPOSITION
  ['ssearrow'] = { 0x2199 },-- SOUTH WEST ARROW
  ['sswarrow'] = { 0x22CF, 0x2191 },-- CURLY LOGICAL AND/UPWARDS ARROW
  ['curlywedgeuparrow'] = { 0x2198 },-- SOUTH EAST ARROW
  ['curlywedgedownarrow'] = { 0x22CF, 0x2193 },-- CURLY LOGICAL AND/DOWNWARDS ARROW
  ['fatslash'] = { 0x2AFD },-- DOUBLE SOLIDUS OPERATOR
  ['fatbslash'] = { 0x244A },-- OCR DOUBLE BACKSLASH
  ['lbag'] = { 0x27C5 },-- LEFT S-SHAPED BAG DELIMITER
  ['rbag'] = { 0x27C6 },-- RIGHT S-SHAPED BAG DELIMITER
  ['varbigcirc'] = { 0x25EF },-- LARGE CIRCLE
  ['leftrightarroweq'] = { 0x2194, 0x0332 },-- LEFT RIGHT ARROW/COMBINING LOW LINE
  ['curlyveedownarrow'] = { 0x22CE, 0x2193 },-- CURLY LOGICAL OR/DOWNWARDS ARROW
  ['curlyveeuparrow'] = { 0x22CE, 0x2191 },-- CURLY LOGICAL OR/UPWARDS ARROW
  ['nnwarrow'] = { 0x2196 },-- NORTH WEST ARROW
  ['nnearrow'] = { 0x2197 },-- NORTH EAST ARROW
  ['leftslice'] = { 0x2AA6 },-- LESS-THAN CLOSED BY CURVE
  ['rightslice'] = { 0x2AA7 },-- GREATER-THAN CLOSED BY CURVE
  ['varolessthan'] = { 0x29C0 },-- CIRCLED LESS-THAN
  ['varogreaterthan'] = { 0x29C1 },-- CIRCLED GREATER-THAN
  ['varovee'] = { 0x2228, 0x20DD },-- LOGICAL OR/COMBINING ENCLOSING CIRCLE
  ['varowedge'] = { 0x2227, 0x20DD },-- LOGICAL AND/COMBINING ENCLOSING CIRCLE
  ['talloblong'] = { 0x2AFF },-- N-ARY WHITE VERTICAL BAR
  ['interleave'] = { 0x2AF4 },-- TRIPLE VERTICAL BAR BINARY RELATION
  ['obar'] = { 0x29B6 },-- CIRCLED VERTICAL BAR
  ['obslash'] = { 0x29B8 },-- CIRCLED REVERSE SOLIDUS
  ['olessthan'] = { 0x29C0 },-- CIRCLED LESS-THAN
  ['ogreaterthan'] = { 0x29C1 },-- CIRCLED GREATER-THAN
  ['ovee'] = { 0x2228, 0x20DD },-- LOGICAL OR/COMBINING ENCLOSING CIRCLE
  ['owedge'] = { 0x2227, 0x20DD },-- LOGICAL AND/COMBINING ENCLOSING CIRCLE
  ['oblong'] = { 0x25AF },-- WHITE VERTICAL RECTANGLE
  ['inplus'] = { 0x2208, 0x207A },-- ELEMENT OF/SUPERSCRIPT PLUS SIGN
  ['niplus'] = { 0x220B, 0x207A },-- CONTAINS AS MEMBER/SUPERSCRIPT PLUS SIGN
  ['nplus'] = { 0x2229, 0x207A },-- INTERSECTION/SUPERSCRIPT PLUS SIGN
  ['subsetplus'] = { 0x2282, 0x207A },-- SUBSET OF/SUPERSCRIPT PLUS SIGN
  ['supsetplus'] = { 0x2283, 0x207A },-- SUPERSET OF/SUPERSCRIPT PLUS SIGN
  ['subsetpluseq'] = { 0x2286, 0x207A },-- SUBSET OF OR EQUAL TO/SUPERSCRIPT PLUS SIGN
  ['supsetpluseq'] = { 0x2287, 0x207A },-- SUPERSET OF OR EQUAL TO/SUPERSCRIPT PLUS SIGN
  ['Lbag'] = { 0x27C5 },-- LEFT S-SHAPED BAG DELIMITER
  ['Rbag'] = { 0x27C6 },-- RIGHT S-SHAPED BAG DELIMITER
  ['llbracket'] = { 0x27E6 },-- MATHEMATICAL LEFT WHITE SQUARE BRACKET
  ['rrbracket'] = { 0x27E7 },-- MATHEMATICAL RIGHT WHITE SQUARE BRACKET
  ['llparenthesis'] = { 0x2985 },-- LEFT WHITE PARENTHESIS
  ['rrparenthesis'] = { 0x2986 },-- RIGHT WHITE PARENTHESIS
  ['binampersand'] = { 0x0026 },-- AMPERSAND
  ['bindnasrepma'] = { 0x214B },-- TURNED AMPERSAND
  ['trianglelefteqslant'] = { 0x22B4 },-- NORMAL SUBGROUP OF OR EQUAL TO
  ['trianglerighteqslant'] = { 0x22B5 },-- CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
  ['ntrianglelefteqslant'] = { 0x22EC },-- NOT NORMAL SUBGROUP OF OR EQUAL TO
  ['ntrianglerighteqslant'] = { 0x22ED },-- DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
  ['llfloor'] = { 0x230A },-- LEFT FLOOR
  ['rrfloor'] = { 0x230B },-- RIGHT FLOOR
  ['llceil'] = { 0x2308 },-- LEFT CEILING
  ['rrceil'] = { 0x2309 },-- RIGHT CEILING
  ['arrownot'] = { 0x0337 },-- COMBINING SHORT SOLIDUS OVERLAY
  ['Arrownot'] = { 0x0337 },-- COMBINING SHORT SOLIDUS OVERLAY
  ['Mapstochar'] = { 0x22A7 },-- MODELS
  ['mapsfromchar'] = { 0x2ADE },-- SHORT LEFT TACK
  ['Mapsfromchar'] = { 0x2AE4 },-- VERTICAL BAR DOUBLE LEFT TURNSTILE
  ['leftrightarrowtriangle'] = { 0x21FF },-- LEFT RIGHT OPEN-HEADED ARROW
  ['leftarrowtriangle'] = { 0x21FD },-- LEFTWARDS OPEN-HEADED ARROW
  ['rightarrowtriangle'] = { 0x21FE },-- RIGHTWARDS OPEN-HEADED ARROW
  ['bigtriangledown'] = { 0x25BD, 0xFE01 },-- WHITE DOWN-POINTING TRIANGLE/VARIATION SELECTOR-2
  ['bigtriangleup'] = { 0x25B3, 0xFE01 },-- WHITE UP-POINTING TRIANGLE/VARIATION SELECTOR-2
  ['bigcurlyvee'] = { 0x22CE, 0xFE02, },-- CURLY LOGICAL OR/VARIATION SELECTOR-3
  ['bigcurlywedge'] = { 0x22CF, 0xFE02, },-- CURLY LOGICAL AND/VARIATION SELECTOR-3
  ['bigsqcap'] = { 0x2293, 0xFE01, },-- SQUARE CAP/VARIATION SELECTOR-2
  ['bigbox'] = { 0x25A1, 0xFE01, },-- WHITE SQUARE/VARIATION SELECTOR-2
  ['bigparallel'] = { 0x2225, 0xFE01, },-- PARALLEL TO/VARIATION SELECTOR-2
  ['biginterleave'] = { 0x2AF4, 0xFE01 },-- TRIPLE VERTICAL BAR BINARY RELATION/VARIATION SELECTOR-2
  ['hugetriangledown'] = { 0x25BD, 0xFE02 },-- WHITE DOWN-POINTING TRIANGLE/VARIATION SELECTOR-3
  ['hugetriangleup'] = { 0x25B3, 0xFE02 },-- WHITE UP-POINTING TRIANGLE/VARIATION SELECTOR-3
  ['hugecurlyvee'] = { 0x22CE, 0xFE03 },-- CURLY LOGICAL OR/VARIATION SELECTOR-4
  ['hugecurlywedge'] = { 0x22CF, 0xFE03 },-- CURLY LOGICAL AND/VARIATION SELECTOR-4
  ['hugesqcap'] = { 0x2293, 0xFE02 },-- SQUARE CAP/VARIATION SELECTOR-3
  ['hugebox'] = { 0x25A1, 0xFE02 },-- WHITE SQUARE/VARIATION SELECTOR-3
  ['hugeparallel'] = { 0x2225, 0xFE02 },-- PARALLEL TO/VARIATION SELECTOR-3
  ['hugeinterleave'] = { 0x2AF4, 0xFE02 },-- TRIPLE VERTICAL BAR BINARY RELATION/VARIATION SELECTOR-3
  ['hugenplus'] = { 0x2229, 0xFE02, 0x207A },-- INTERSECTION/VARIATION SELECTOR-3/SUPERSCRIPT PLUS SIGN
  ['largellbracket'] = { 0x27E6, 0xFE01 },-- MATHEMATICAL LEFT WHITE SQUARE BRACKET/VARIATION SELECTOR-2
  ['Largellbracket'] = { 0x27E6, 0xFE02 },-- MATHEMATICAL LEFT WHITE SQUARE BRACKET/VARIATION SELECTOR-3
  ['LARGEllbracket'] = { 0x27E6, 0xFE03 },-- MATHEMATICAL LEFT WHITE SQUARE BRACKET/VARIATION SELECTOR-4
  ['hugellbracket'] = { 0x27E6, 0xFE04 },-- MATHEMATICAL LEFT WHITE SQUARE BRACKET/VARIATION SELECTOR-5
  ['Hugellbrackettop'] = { 0x23A1 },-- LEFT SQUARE BRACKET UPPER CORNER
  ['Hugellbracketbot'] = { 0x23A3 },-- LEFT SQUARE BRACKET LOWER CORNER
  ['Hugellbracketex'] = { 0x23F8 },-- DOUBLE VERTICAL BAR
  ['Hugenplus'] = { 0x2229, 0xFE03, 0x207A },-- INTERSECTION/VARIATION SELECTOR-4/SUPERSCRIPT PLUS SIGN
  ['largerrbracket'] = { 0x27E7, 0xFE01 },-- MATHEMATICAL RIGHT WHITE SQUARE BRACKET/VARIATION SELECTOR-2
  ['Largerrbracket'] = { 0x27E7, 0xFE02 },-- MATHEMATICAL RIGHT WHITE SQUARE BRACKET/VARIATION SELECTOR-3
  ['LARGErrbracket'] = { 0x27E7, 0xFE03 },-- MATHEMATICAL RIGHT WHITE SQUARE BRACKET/VARIATION SELECTOR-4
  ['hugerrbracket'] = { 0x27E7, 0xFE04 },-- MATHEMATICAL RIGHT WHITE SQUARE BRACKET/VARIATION SELECTOR-5
  ['Hugerrbrackettop'] = { 0x23A4, },-- RIGHT SQUARE BRACKET UPPER CORNER
  ['Hugerrbracketbot'] = { 0x23A6 },-- RIGHT SQUARE BRACKET LOWER CORNER
  ['Hugerrbracketex'] = { 0x23F8 },-- DOUBLE VERTICAL BAR
  }