return {
  ['Gamma'] = { 0x1D71E, },-- MATHEMATICAL BOLD ITALIC CAPITAL GAMMA
  ['Delta'] = { 0x1D71F, },-- MATHEMATICAL BOLD ITALIC CAPITAL DELTA
  ['Theta'] = { 0x1D723, },-- MATHEMATICAL BOLD ITALIC CAPITAL THETA
  ['Lambda'] = { 0x1D726, },-- MATHEMATICAL BOLD ITALIC CAPITAL LAMDA
  ['Xi'] = { 0x1D729, },-- MATHEMATICAL BOLD ITALIC CAPITAL XI
  ['Pi'] = { 0x1D72B, },-- MATHEMATICAL BOLD ITALIC CAPITAL PI
  ['Sigma'] = { 0x1D72E, },-- MATHEMATICAL BOLD ITALIC CAPITAL SIGMA
  ['Upsilon'] = { 0x1D730, },-- MATHEMATICAL BOLD ITALIC CAPITAL UPSILON
  ['Phi'] = { 0x1D731, },-- MATHEMATICAL BOLD ITALIC CAPITAL PHI
  ['Psi'] = { 0x1D733, },-- MATHEMATICAL BOLD ITALIC CAPITAL PSI
  ['Omega'] = { 0x1D734, },-- MATHEMATICAL BOLD ITALIC CAPITAL OMEGA
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  }