return {
  ['mapsfrom'] = { 0x2ADE },-- SHORT LEFT TACK
  ['Mapsto'] = { 0x22A7 },-- MODELS
  ['Mapsfrom'] = { 0x2AE4 },-- VERTICAL BAR DOUBLE LEFT TURNSTILE
  ['mmapsto'] = { 0x22a9 },-- Code not found in UnicodeData
  ['mmapsfrom'] = { 0x2AE3 },-- DOUBLE VERTICAL BAR LEFT TURNSTILE
  ['Mmapsto'] = { 0x22AB },-- DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
  ['Mmapsfrom'] = { 0x2AE5 },-- DOUBLE VERTICAL BAR DOUBLE LEFT TURNSTILE
  ['medcircle'] = { 0x1F785 },-- MEDIUM BOLD WHITE CIRCLE
  ['medbullet'] = { 0x25CF },-- BLACK CIRCLE
  ['parallel'] = { 0x2AFD },-- DOUBLE SOLIDUS OPERATOR
  ['parallel1'] = { 0x244A },-- OCR DOUBLE BACKSLASH
  ['nparallel'] = { 0x2AFD, 0x0335 },-- DOUBLE SOLIDUS OPERATOR/COMBINING SHORT STROKE OVERLAY
  ['nparallel1'] = { 0x244A, 0x0335 },-- OCR DOUBLE BACKSLASH/COMBINING SHORT STROKE OVERLAY
  ['colonapprox'] = { 0x003A, 0x2248 },-- COLON/ALMOST EQUAL TO
  ['colonsim'] = { 0x003A, 0x223C },-- COLON/TILDE OPERATOR
  ['coloncolonapprox'] = { 0x003A, 0x003A, 0x2248 },-- COLON/COLON/ALMOST EQUAL TO
  ['coloncolonsim'] = { 0x003A, 0x003A, 0x223C },-- COLON/COLON/TILDE OPERATOR
  ['doteq'] = { 0x2250 },-- APPROACHES THE LIMIT
  ['multimapinv'] = { 0x27DC },-- LEFT MULTIMAP
  ['multimapboth'] = { 0x29DF },-- DOUBLE-ENDED MULTIMAP
  ['solidmultimap'] = { 0x2015, 0x2219 },-- HORIZONTAL BAR/BULLET OPERATOR
  ['solidmultimapinv'] = { 0x2219, 0x2015 },-- BULLET OPERATOR/HORIZONTAL BAR
  ['solidmultimapboth'] = { 0x2219, 0x2015, 0x2219 },-- BULLET OPERATOR/HORIZONTAL BAR/BULLET OPERATOR
  ['rsolidmultimapboth'] = { 0x22B6 },-- ORIGINAL OF
  ['lsolidmultimapboth'] = { 0x22B7 },-- IMAGE OF
  ['forcesextra'] = { 0x22AB },-- DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
  ['Forcesbar'] = { 0x23F8, 0x22A7 },-- DOUBLE VERTICAL BAR/MODELS
  ['simequal'] = { 0x2245 },-- APPROXIMATELY EQUAL TO
  ['precedesordblequal'] = { 0x2AB3 },-- PRECEDES ABOVE EQUALS SIGN
  ['followsordblequal'] = { 0x2AB4 },-- SUCCEEDS ABOVE EQUALS SIGN
  ['notprecedesorsimilar'] = { 0x227E, 0x0338 },-- PRECEDES OR EQUIVALENT TO/COMBINING LONG SOLIDUS OVERLAY
  ['notfollowsorsimilar'] = { 0x227F, 0x0338 },-- SUCCEEDS OR EQUIVALENT TO/COMBINING LONG SOLIDUS OVERLAY
  ['notlessorsimilar'] = { 0x2274 },-- NEITHER LESS-THAN NOR EQUIVALENT TO
  ['notgreaterorsimilar'] = { 0x2275 },-- NEITHER GREATER-THAN NOR EQUIVALENT TO
  ['notlessorapproxeql'] = { 0x2a85, 0x0338 },-- Code not found in UnicodeData/COMBINING LONG SOLIDUS OVERLAY
  ['notgreaterorapproxeql'] = { 0x2A86, 0x0338 },-- GREATER-THAN OR APPROXIMATE/COMBINING LONG SOLIDUS OVERLAY
  ['notprecedesorcurly'] = { 0x22E0 },-- DOES NOT PRECEDE OR EQUAL
  ['notfollowsorcurly'] = { 0x22E1 },-- DOES NOT SUCCEED OR EQUAL
  ['notgreaterorless'] = { 0x2278 },-- NEITHER LESS-THAN NOR GREATER-THAN
  ['notlessorgreater'] = { 0x2279 },-- NEITHER GREATER-THAN NOR LESS-THAN
  ['notdifference'] = { 0x224F, 0x0338 },-- DIFFERENCE BETWEEN/COMBINING LONG SOLIDUS OVERLAY
  ['notgeomequivalent'] = { 0x224E, 0x0338 },-- GEOMETRICALLY EQUIVALENT TO/COMBINING LONG SOLIDUS OVERLAY
  ['notrevsimilar'] = { 0x223D, 0x0337 },-- REVERSED TILDE/COMBINING SHORT SOLIDUS OVERLAY
  ['notrevasymptequal'] = { 0x22CD, 0x0338 },-- REVERSED TILDE EQUALS/COMBINING LONG SOLIDUS OVERLAY
  ['nequal'] = { 0x2260 },-- NOT EQUAL TO
  ['nequivasymptotic'] = { 0x226D },-- NOT EQUIVALENT TO
  ['nequivalence'] = { 0x2262 },-- NOT IDENTICAL TO
  ['nsimilar'] = { 0x2241 },-- NOT TILDE
  ['napproxequal'] = { 0x2249 },-- NOT ALMOST EQUAL TO
  ['npropersubset'] = { 0x2284 },-- NOT A SUBSET OF
  ['npropersuperset'] = { 0x2285 },-- NOT A SUPERSET OF
  ['nlessmuch'] = { 0x226A, 0x0338 },-- MUCH LESS-THAN/COMBINING LONG SOLIDUS OVERLAY
  ['ngreatermuch'] = { 0x226B, 0x0338 },-- MUCH GREATER-THAN/COMBINING LONG SOLIDUS OVERLAY
  ['notapproxequal'] = { 0x2249 },-- NOT ALMOST EQUAL TO
  ['notapproxorequal'] = { 0x224a, 0x0338 },-- Code not found in UnicodeData/COMBINING LONG SOLIDUS OVERLAY
  ['notfollowsorequal'] = { 0x2AB7, 0x0338 },-- PRECEDES ABOVE ALMOST EQUAL TO/COMBINING LONG SOLIDUS OVERLAY
  ['notprecedesorequal'] = { 0x2AB8, 0x0338 },-- SUCCEEDS ABOVE ALMOST EQUAL TO/COMBINING LONG SOLIDUS OVERLAY
  ['notprecedesordblequal'] = { 0x2AB3, 0x0338 },-- PRECEDES ABOVE EQUALS SIGN/COMBINING LONG SOLIDUS OVERLAY
  ['notfollowsordblequal'] = { 0x2AB4, 0x0338 },-- SUCCEEDS ABOVE EQUALS SIGN/COMBINING LONG SOLIDUS OVERLAY
  ['nsimilarequal'] = { 0x2244 },-- NOT ASYMPTOTICALLY EQUAL TO
  ['nelement'] = { 0x2209 },-- NOT AN ELEMENT OF
  ['nowner'] = { 0x220C },-- DOES NOT CONTAIN AS MEMBER
  ['notsubsetdbl'] = { 0x22D0, 0x0338 },-- DOUBLE SUBSET/COMBINING LONG SOLIDUS OVERLAY
  ['notsupersetdbl'] = { 0x22D1, 0x0338 },-- DOUBLE SUPERSET/COMBINING LONG SOLIDUS OVERLAY
  ['nsubsetsqequal'] = { 0x22E2 },-- NOT SQUARE IMAGE OF OR EQUAL TO
  ['nsupersetsqequal'] = { 0x22E3 },-- NOT SQUARE ORIGINAL OF OR EQUAL TO
  ['colonequal'] = { 0x2254 },-- COLON EQUALS
  ['equalcolon'] = { 0x2255 },-- EQUALS COLON
  ['colonbar'] = { 0x003A, 0x2212 },-- COLON/MINUS SIGN
  ['barcolon'] = { 0x2239 },-- EXCESS
  ['Colonequal'] = { 0x2A74 },-- DOUBLE COLON EQUAL
  ['Equalcolon'] = { 0x2255, 0x003A },-- EQUALS COLON/COLON
  ['Colonbar'] = { 0x003A, 0x003A, 0x2212 },-- COLON/COLON/MINUS SIGN
  ['Barcolon'] = { 0x2239, 0x003A },-- EXCESS/COLON
  ['strict'] = { 0x297D },-- RIGHT FISH TAIL
  ['strictinverse'] = { 0x297C },-- LEFT FISH TAIL
  ['strictboth'] = { 0x297C, 0x297D },-- LEFT FISH TAIL/RIGHT FISH TAIL
  ['ampersandinv'] = { 0x214B },-- TURNED AMPERSAND
  ['lbag'] = { 0x27C5 },-- LEFT S-SHAPED BAG DELIMITER
  ['rbag'] = { 0x27C6 },-- RIGHT S-SHAPED BAG DELIMITER
  ['lbagbig'] = { 0x27C5, 0xFE01 },-- LEFT S-SHAPED BAG DELIMITER/VARIATION SELECTOR-2
  ['rbagbig'] = { 0x27C6, 0xFE01},-- RIGHT S-SHAPED BAG DELIMITER/VARIATION SELECTOR-2
  ['oless'] = { 0x29C0 },-- CIRCLED LESS-THAN
  ['ogreater'] = { 0x29C1 },-- CIRCLED GREATER-THAN
  ['owedge'] = { 0x2227, 0x20DD },-- LOGICAL AND/COMBINING ENCLOSING CIRCLE
  ['ovee'] = { 0x2228, 0x20DD },-- LOGICAL OR/COMBINING ENCLOSING CIRCLE
  ['circlebar'] = { 0x29B6 },-- CIRCLED VERTICAL BAR
  ['circlebackslash'] = { 0x29B8 },-- CIRCLED REVERSE SOLIDUS
  ['multicloseleft1'] = { 0x22C9 },-- LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
  ['multicloseright1'] = { 0x22CA },-- RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
  ['multicloseboth1'] = { 0x22C8 },-- BOWTIE
  ['multiopenboth1'] = { 0x2A09 },-- N-ARY TIMES OPERATOR
  ['multicloseboth'] = { 0x22C8 },-- BOWTIE
  ['multiopenboth'] = { 0x2A09 },-- N-ARY TIMES OPERATOR
  ['Diamond'] = { 0x25C7 },-- WHITE DIAMOND
  ['Diamondsolid'] = { 0x25C6 },-- BLACK DIAMOND
  ['intersectmulti'] = { 0x2229, 0x207A },-- INTERSECTION/SUPERSCRIPT PLUS SIGN
  ['notsquareimage'] = { 0x228F, 0x0338 },-- SQUARE IMAGE OF/COMBINING LONG SOLIDUS OVERLAY
  ['notsquareoriginal'] = { 0x2290, 0x0338 },-- SQUARE ORIGINAL OF/COMBINING LONG SOLIDUS OVERLAY
  ['dashedarrowleft'] = { 0x21E0 },-- LEFTWARDS DASHED ARROW
  ['dashedarrowright'] = { 0x21E2 },-- RIGHTWARDS DASHED ARROW
  ['dashedarrowboth'] = { 0x21E0, 0x21E2 },-- LEFTWARDS DASHED ARROW/RIGHTWARDS DASHED ARROW
  ['squiggleleft'] = { 0x21DC },-- LEFTWARDS SQUIGGLE ARROW
  ['notdblarrowheadright'] = { 0x2900 },-- RIGHTWARDS TWO-HEADED ARROW WITH VERTICAL STROKE
  ['notdblarrowheadleft'] = { 0x2B34 },-- LEFTWARDS TWO-HEADED ARROW WITH VERTICAL STROKE
  ['squareasterisk'] = { 0x29C6 },-- SQUARED ASTERISK
  ['squarebackslash'] = { 0x29C5 },-- SQUARED FALLING DIAGONAL SLASH
  ['squarebar'] = { 0x25EB },-- WHITE SQUARE WITH VERTICAL BISECTING LINE
  ['squareslash'] = { 0x29C4 },-- SQUARED RISING DIAGONAL SLASH
  ['Wreathproduct'] = { 0x2240, 0x2240 },-- WREATH PRODUCT/WREATH PRODUCT
  ['lambdaslash'] = { 0x019B },-- LATIN SMALL LETTER LAMBDA WITH STROKE
  ['lambdabar'] = { 0x019B },-- LATIN SMALL LETTER LAMBDA WITH STROKE
  ['club1'] = { 0x2667 },-- WHITE CLUB SUIT
  ['diamond1'] = { 0x2666 },-- BLACK DIAMOND SUIT
  ['heart1'] = { 0x2665 },-- BLACK HEART SUIT
  ['spade1'] = { 0x2664 },-- WHITE SPADE SUIT
  ['Arrownortheast'] = { 0x21D7 },-- NORTH EAST DOUBLE ARROW
  ['Arrowsoutheast'] = { 0x21D8 },-- SOUTH EAST DOUBLE ARROW
  ['Arrownorthwest'] = { 0x21D6 },-- NORTH WEST DOUBLE ARROW
  ['Arrowsouthwest'] = { 0x21D9 },-- SOUTH WEST DOUBLE ARROW
  ['Latticetop'] = { 0x2AEA },-- DOUBLE DOWN TACK
  ['Perpendicular'] = { 0x2AEB },-- DOUBLE UP TACK
  ['leadstoext'] = { 0x223c },-- Code not found in UnicodeData
  ['leadsto'] = { 0x219D },-- RIGHTWARDS WAVE ARROW
  ['squareunionmulti'] = { 0x2294, 0x207A },-- SQUARE CUP/SUPERSCRIPT PLUS SIGN
  ['squareintersectmulti'] = { 0x2293, 0x207A },-- SQUARE CAP/SUPERSCRIPT PLUS SIGN
  ['squareright'] = { 0x25AB, 0x2192 },-- WHITE SMALL SQUARE/RIGHTWARDS ARROW
  ['squareleft'] = { 0x2190, 0x25AB },-- LEFTWARDS ARROW/WHITE SMALL SQUARE
  ['squaredotright'] = { 0x22A1, 0x2192 },-- SQUARED DOT OPERATOR/RIGHTWARDS ARROW
  ['squaredotleft'] = { 0x2190, 0x22A1 },-- LEFTWARDS ARROW/SQUARED DOT OPERATOR
  ['Diamondright'] = { 0x25C7, 0x2192 },-- WHITE DIAMOND/RIGHTWARDS ARROW
  ['Diamondleft'] = { 0x2190, 0x25C7 },-- LEFTWARDS ARROW/WHITE DIAMOND
  ['Diamonddotright'] = { 0x27D0, 0x2192 },-- WHITE DIAMOND WITH CENTRED DOT/RIGHTWARDS ARROW
  ['Diamonddotleft'] = { 0x2190, 0x27D0 },-- LEFTWARDS ARROW/WHITE DIAMOND WITH CENTRED DOT
  ['squareRight'] = { 0x25AB, 0x21D2 },-- WHITE SMALL SQUARE/RIGHTWARDS DOUBLE ARROW
  ['squareLeft'] = { 0x21D0, 0x25AB },-- LEFTWARDS DOUBLE ARROW/WHITE SMALL SQUARE
  ['squaredotRight'] = { 0x22A1, 0x21D2 },-- SQUARED DOT OPERATOR/RIGHTWARDS DOUBLE ARROW
  ['squaredotLeft'] = { 0x21D0, 0x22A1 },-- LEFTWARDS DOUBLE ARROW/SQUARED DOT OPERATOR
  ['DiamondRight'] = { 0x25C7, 0x21D2 },-- WHITE DIAMOND/RIGHTWARDS DOUBLE ARROW
  ['DiamondLeft'] = { 0x21D0, 0x25C7 },-- LEFTWARDS DOUBLE ARROW/WHITE DIAMOND
  ['DiamonddotRight'] = { 0x27D0, 0x21D2 },-- WHITE DIAMOND WITH CENTRED DOT/RIGHTWARDS DOUBLE ARROW
  ['DiamonddotLeft'] = { 0x21D0, 0x27D0 },-- LEFTWARDS DOUBLE ARROW/WHITE DIAMOND WITH CENTRED DOT
  ['Diamonddot'] = { 0x27D0 },-- WHITE DIAMOND WITH CENTRED DOT
  ['circleright'] = { 0x25CB, 0x2192 },-- WHITE CIRCLE/RIGHTWARDS ARROW
  ['circleleft'] = { 0x2190, 0x25CB },-- LEFTWARDS ARROW/WHITE CIRCLE
  ['circledotright'] = { 0x2299, 0x2192 },-- CIRCLED DOT OPERATOR/RIGHTWARDS ARROW
  ['circledotleft'] = { 0x2190, 0x2299 },-- LEFTWARDS ARROW/CIRCLED DOT OPERATOR
  ['opentrans'] = { 0x29DF, 0x20D5 },-- DOUBLE-ENDED MULTIMAP/COMBINING CLOCKWISE ARROW ABOVE
  ['solidtrans'] = { 0x2219, 0x007C, 0x2219 },-- BULLET OPERATOR/VERTICAL LINE/BULLET OPERATOR
  ['topsolidtrans'] = { 0x22B7, 0x20D5 },-- IMAGE OF/COMBINING CLOCKWISE ARROW ABOVE
  ['topopentrans'] = { 0x22B6, 0x20D5 },-- ORIGINAL OF/COMBINING CLOCKWISE ARROW ABOVE
  }
