return {
  ['.notdef'] = { 0x0020 },-- SPACE
  ['zero.superior'] = { 0x2070, 'zerosuperscript' },-- SUPERSCRIPT ZERO
  ['one.superior'] = { 0x00B9, 'onesuperscript' },-- SUPERSCRIPT ONE
  ['two.superior'] = { 0x00B2, 'twosuperscript' },-- SUPERSCRIPT TWO
  ['three.superior'] = { 0x00B3, 'threesuperscript' },-- SUPERSCRIPT THREE
  ['four.superior'] = { 0x2074, 'foursuperscript' },-- SUPERSCRIPT FOUR
  ['five.superior'] = { 0x2075, 'fivesuperscript' },-- SUPERSCRIPT FIVE
  ['six.superior'] = { 0x2076, 'sixsuperscript' },-- SUPERSCRIPT SIX
  ['seven.superior'] = { 0x2077, 'sevensuperscript' },-- SUPERSCRIPT SEVEN
  ['eight.superior'] = { 0x2078, 'eightsuperscript' },-- SUPERSCRIPT EIGHT
  ['nine.superior'] = { 0x2079, 'ninesuperscript' },-- SUPERSCRIPT NINE
  ['a.superior'] = { 0x1D43, 'asuperscript' },-- MODIFIER LETTER SMALL A
  ['b.superior'] = { 0x1D47, 'bsuperscript' },-- MODIFIER LETTER SMALL B
  ['c.superior'] = { 0x1D9C, 'csuperscript' },-- MODIFIER LETTER SMALL C
  ['d.superior'] = { 0x1D48, 'dsuperscript' },-- MODIFIER LETTER SMALL D
  ['e.superior'] = { 0x1D49, 'esuperscript' },-- MODIFIER LETTER SMALL E
  ['f.superior'] = { 0x1DA0, 'fsuperscript' },-- MODIFIER LETTER SMALL F
  ['g.superior'] = { 0x1D4D, 'gsuperscript' },-- MODIFIER LETTER SMALL G
  ['h.superior'] = { 0x02B0, 'hsuperscript' },-- MODIFIER LETTER SMALL H
  ['hhook.superior'] = { 0x02B1, 'hhooksuperscript' },-- MODIFIER LETTER SMALL H WITH HOOK
  ['i.superior'] = { 0x2071, 'isuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['j.superior'] = { 0x02B2, 'jsuperscript' },-- MODIFIER LETTER SMALL J
  ['k.superior'] = { 0x1D4F, 'ksuperscript' },-- MODIFIER LETTER SMALL K
  ['l.superior'] = { 0x02E1, 'lsuperscript' },-- MODIFIER LETTER SMALL L
  ['m.superior'] = { 0x1D50, 'msuperscript' },-- MODIFIER LETTER SMALL M
  ['n.superior'] = { 0x207F, 'nsuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER N
  ['o.superior'] = { 0x1D52, 'osuperscript' },-- MODIFIER LETTER SMALL O
  ['p.superior'] = { 0x1D56, 'psuperscript' },-- MODIFIER LETTER SMALL P
  ['q.superior'] = { 0x107A5, 'qsuperscript' },-- MODIFIER LETTER SMALL Q
  ['r.superior'] = { 0x02B3, 'rsuperscript' },-- MODIFIER LETTER SMALL R
  ['rhookturned.superior'] = { 0x02B5, 'rhookturnedsuperscript' },-- MODIFIER LETTER SMALL TURNED R WITH HOOK
  ['rturned.superior'] = { 0x02B4, 'rturnedsuperscript' },-- MODIFIER LETTER SMALL TURNED R
  ['Rsmallinverted.superior'] = { 0x02B6, 'Rsmallinvertedsuperscript'},-- MODIFIER LETTER SMALL CAPITAL INVERTED R
  ['s.superior'] = { 0x02E2, 'ssuperscript' },-- MODIFIER LETTER SMALL S
  ['t.superior'] = { 0x1D57, 'tsuperscript' },-- MODIFIER LETTER SMALL T
  ['u.superior'] = { 0x1D58, 'usuperscript' },-- MODIFIER LETTER SMALL U
  ['v.superior'] = { 0x1D5B, 'vsuperscript' },-- MODIFIER LETTER SMALL V
  ['w.superior'] = { 0x02B7, 'wsuperscript' },-- MODIFIER LETTER SMALL W
  ['x.superior'] = { 0x02E3, 'xsuperscript' },-- MODIFIER LETTER SMALL X
  ['y.superior'] = { 0x02B8, 'ysuperscript' },-- MODIFIER LETTER SMALL Y
  ['z.superior'] = { 0x1DBB, 'zsuperscript' },-- MODIFIER LETTER SMALL Z
  ['plus.superior'] = { 0x207A, 'plussuperscript' },-- SUPERSCRIPT PLUS SIGN
  ['minus.superior'] = { 0x207B, 'minussuperscript' },-- SUPERSCRIPT MINUS
  ['equal.superior'] = { 0x207C, 'equalsuperscript' },-- SUPERSCRIPT EQUALS SIGN
  ['parenleft.superior'] = { 0x207D, 'parenleftsuperscript' },-- SUPERSCRIPT LEFT PARENTHESIS
  ['parenright.superior'] = { 0x207E, 'parenrightsuperscript' },-- SUPERSCRIPT RIGHT PARENTHESIS
  ['gammalatin.superior'] = { 0x02E0, 'gammasuperscript' },-- MODIFIER LETTER SMALL GAMMA
  ['glottalstopreversed.superior'] = { 0x02E4, 'glottalstopreversedsuperscript' },-- MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
  ['zero.inferior'] = { 0x2080, 'zerosubscript' },-- SUBSCRIPT ZERO
  ['one.inferior'] = { 0x2081, 'onesubscript' },-- SUBSCRIPT ONE
  ['two.inferior'] = { 0x2082, 'twosubscript' },-- SUBSCRIPT TWO
  ['three.inferior'] = { 0x2083, 'threesubscript' },-- SUBSCRIPT THREE
  ['four.inferior'] = { 0x2084, 'foursubscript' },-- SUBSCRIPT FOUR
  ['five.inferior'] = { 0x2085, 'fivesubscript' },-- SUBSCRIPT FIVE
  ['six.inferior'] = { 0x2086, 'sixsubscript' },-- SUBSCRIPT SIX
  ['seven.inferior'] = { 0x2087, 'sevensubscript' },-- SUBSCRIPT SEVEN
  ['eight.inferior'] = { 0x2088, 'eightsubscript' },-- SUBSCRIPT EIGHT
  ['nine.inferior'] = { 0x2089, 'ninesubscript' },-- SUBSCRIPT NINE
  ['plus.inferior'] = { 0x208A, 'plussubscript' },-- SUBSCRIPT PLUS SIGN
  ['minus.inferior'] = { 0x208B, 'minussubscript' },-- SUBSCRIPT MINUS
  ['equal.inferior'] = { 0x208C, 'equalsubscript' },-- SUBSCRIPT EQUALS SIGN
  ['parenleft.inferior'] = { 0x208D, 'parenleftsubscript' },-- SUBSCRIPT LEFT PARENTHESIS
  ['parenright.inferior'] = { 0x208E, 'parenrightsubscript' },-- SUBSCRIPT RIGHT PARENTHESIS
  ['a.inferior'] = { 0x2090, 'asubscript' },-- LATIN SUBSCRIPT SMALL LETTER A
  ['e.inferior'] = { 0x2091, 'esubscript' },-- LATIN SUBSCRIPT SMALL LETTER E
  ['h.inferior'] = { 0x2095, 'hsubscript' },-- LATIN SUBSCRIPT SMALL LETTER H
  ['i.inferior'] = { 0x1D62, 'isubscript' },-- LATIN SUBSCRIPT SMALL LETTER I
  ['j.inferior'] = { 0x2C7C, 'jsubscript' },-- LATIN SUBSCRIPT SMALL LETTER J
  ['k.inferior'] = { 0x2096, 'ksubscript' },-- LATIN SUBSCRIPT SMALL LETTER K
  ['l.inferior'] = { 0x2097, 'lsubscript' },-- LATIN SUBSCRIPT SMALL LETTER L
  ['m.inferior'] = { 0x2098, 'msubscript' },-- LATIN SUBSCRIPT SMALL LETTER M
  ['n.inferior'] = { 0x2099, 'nsubscript' },-- LATIN SUBSCRIPT SMALL LETTER N
  ['o.inferior'] = { 0x2092, 'osubscript' },-- LATIN SUBSCRIPT SMALL LETTER O
  ['p.inferior'] = { 0x209A, 'psubscript' },-- LATIN SUBSCRIPT SMALL LETTER P
  ['r.inferior'] = { 0x1D63, 'rsubscript' },-- LATIN SUBSCRIPT SMALL LETTER R
  ['s.inferior'] = { 0x209B, 'ssubscript' },-- LATIN SUBSCRIPT SMALL LETTER S
  ['t.inferior'] = { 0x209C, 'tsubscript' },-- LATIN SUBSCRIPT SMALL LETTER T
  ['u.inferior'] = { 0x1D64, 'usubscript' },-- LATIN SUBSCRIPT SMALL LETTER U
  ['v.inferior'] = { 0x1D65, 'vsubscript' },-- LATIN SUBSCRIPT SMALL LETTER V
  ['x.inferior'] = { 0x2093, 'xsubscript' },-- LATIN SUBSCRIPT SMALL LETTER X
  ['enquad'] = { 0x2000 },-- EN QUAD
  ['emquad'] = { 0x2001 },-- EM QUAD
  ['emspace'] = { 0x2003 },-- EM SPACE
  ['threeperemspace'] = { 0x2004 },-- THREE-PER-EM SPACE
  ['fourperemspace'] = { 0x2005 },-- FOUR-PER-EM SPACE
  ['sixperemspace'] = { 0x2006 },-- SIX-PER-EM SPACE
  ['figurespace'] = { 0x2007 },-- FIGURE SPACE
  ['punctuationspace'] = { 0x2008 },-- PUNCTUATION SPACE
  ['thinspace'] = { 0x2009 },-- THIN SPACE
  ['hairspace'] = { 0x200A },-- HAIR SPACE
  ['quotedblrev'] = { 0x201F },-- DOUBLE HIGH-REVERSED-9 QUOTATION MARK
  ['onefifth'] = { 0x2155 },-- VULGAR FRACTION ONE FIFTH
  ['twofifths'] = { 0x2156 },-- VULGAR FRACTION TWO FIFTHS
  ['threefifths'] = { 0x2157 },-- VULGAR FRACTION THREE FIFTHS
  ['fourfifths'] = { 0x2158 },-- VULGAR FRACTION FOUR FIFTHS
  ['onenumerator'] = { 0x215F },-- FRACTION NUMERATOR ONE
  ['Nwarrow'] = { 0x21D6 },-- NORTH WEST DOUBLE ARROW
  ['Nearrow'] = { 0x21D7 },-- NORTH EAST DOUBLE ARROW
  ['Searrow'] = { 0x21D8 },-- SOUTH EAST DOUBLE ARROW
  ['Swarrow'] = { 0x21D9 },-- SOUTH WEST DOUBLE ARROW
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['hyphennobreak'] = { 0x2011 },-- NON-BREAKING HYPHEN
  ['trianglebullet'] = { 0x2023 },-- TRIANGULAR BULLET
  ['hyphendot'] = { 0x2027 },-- HYPHENATION POINT
  ['primetriple'] = { 0x2034 },-- TRIPLE PRIME
  ['onesixth'] = { 0x2159 },-- VULGAR FRACTION ONE SIXTH
  ['fivesixths'] = { 0x215A },-- VULGAR FRACTION FIVE SIXTHS
  ['perthousandzero'] = { 0x2080 },-- SUBSCRIPT ZERO
  ['gammalatin'] = { 0x0263 },-- LATIN SMALL LETTER GAMMA
  ['Rsmallcap'] = { 0x0280, },-- LATIN LETTER SMALL CAPITAL R
  ['a.sc'] = { 0x1D00, 'aSC' },-- LATIN LETTER SMALL CAPITAL A
  ['a.scalt'] = { 0x1D00, 'aSCalt' },-- LATIN LETTER SMALL CAPITAL A
  ['aacute.sc'] = { 0x1D00, 0x0301, 'AacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING ACUTE ACCENT
  ['abreve.sc'] = { 0x1D00, 0x0306, 'AbreveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE
  ['acircumflex.sc'] = { 0x1D00, 0x0302, 'AcircumflexSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT
  ['adieresis.sc'] = { 0x1D00, 0x0308, 'AdieresisSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DIAERESIS
  ['ae.sc'] = { 0x1D01, 'AESC' },-- LATIN LETTER SMALL CAPITAL AE
  ['agrave.sc'] = { 0x1D00, 0x0300, 'AgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING GRAVE ACCENT
  ['aogonek.sc'] = { 0x1D00, 0x0328, 'AogonekSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK
  ['aring.sc'] = { 0x1D00, 0x030A, 'AringSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE
  ['atilde.sc'] = { 0x1D00, 0x0303, 'AtildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING TILDE
  ['b.sc'] = { 0x0299, 'bSC' },-- LATIN LETTER SMALL CAPITAL B
  ['c.sc'] = { 0x1D04, 'cSC' },-- LATIN LETTER SMALL CAPITAL C
  ['cacute.sc'] = { 0x1D04, 0x0301, 'CacuteSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING ACUTE ACCENT
  ['ccaron.sc'] = { 0x1D04, 0x030C, 'CcaronSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CARON
  ['ccedilla.sc'] = { 0x1D04, 0x0327, 'CcedillaSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CEDILLA
  ['d.sc'] = { 0x1D05, 'dSC' },-- LATIN LETTER SMALL CAPITAL D
  ['dcaron.sc'] = { 0x1D05, 0x030C, 'DcaronSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING CARON
  ['e.sc'] = { 0x1D07, 'eSC' },-- LATIN LETTER SMALL CAPITAL E
  ['eacute.sc'] = { 0x1D07, 0x0301, 'EacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING ACUTE ACCENT
  ['ecaron.sc'] = { 0x1D07, 0x030C, 'EcaronSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CARON
  ['ecircumflex.sc'] = { 0x1D07, 0x0302, 'EcircumflexSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT
  ['edieresis.sc'] = { 0x1D07, 0x0308, 'EdieresisSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DIAERESIS
  ['egrave.sc'] = { 0x1D07, 0x0300, 'EgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING GRAVE ACCENT
  ['eogonek.sc'] = { 0x1D07, 0x0328, 'EogonekSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK
  ['eth.sc'] = { 0x1D06, 'etchSC' },-- LATIN LETTER SMALL CAPITAL ETH
  ['f.sc'] = { 0xA730, 'fSC' },-- LATIN LETTER SMALL CAPITAL F
  ['g.sc'] = { 0x0262, 'gSC' },-- LATIN LETTER SMALL CAPITAL G
  ['gbreve.sc'] = { 0x0262, 0x0306, 'GbreveSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING BREVE
  ['germandbls.scalt'] = { 0xA731, 0xA731, 'germandblsSCalt' },-- LATIN LETTER SMALL CAPITAL S/LATIN LETTER SMALL CAPITAL S
  ['germandbls.ss03'] = { 0x0073, 0x0073, 'germandblsSS' },-- LATIN SMALL LETTER S/LATIN SMALL LETTER S
  ['h.sc'] = { 0x029C, 'hSC' },-- LATIN LETTER SMALL CAPITAL H
  ['i.sc'] = { 0x026A, 'iSC' },-- LATIN LETTER SMALL CAPITAL I
  ['iacute.sc'] = { 0x026A, 0x0301, 'IacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING ACUTE ACCENT
  ['icircumflex.sc'] = { 0x026A, 0x0302, 'IcircumflexSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CIRCUMFLEX ACCENT
  ['idieresis.sc'] = { 0x026A, 0x0308, 'IdieresisSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS
  ['idotaccent.sc'] = { 0x026A, 0x0307, 'IdotaccentSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT ABOVE
  ['igrave.sc'] = { 0x026A, 0x0300, 'IgraveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING GRAVE ACCENT
  ['ij.sc'] = { 0x026A, 0x1D0A },-- LATIN LETTER SMALL CAPITAL I/LATIN LETTER SMALL CAPITAL J
  ['j.sc'] = { 0x1D0A, 'jSC' },-- LATIN LETTER SMALL CAPITAL J
  ['k.sc'] = { 0x1D0B, 'kSC' },-- LATIN LETTER SMALL CAPITAL K
  ['l.sc'] = { 0x029F, 'lSC' },-- LATIN LETTER SMALL CAPITAL L
  ['lacute.sc'] = { 0x029F, 0x0301, 'LacuteSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING ACUTE ACCENT
  ['lcaron.sc'] = { 0x029F, 0x0315, 'LcaronSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA ABOVE RIGHT
  ['lslash.sc'] = { 0x1D0C, 'LslashSC' },-- LATIN LETTER SMALL CAPITAL L WITH STROKE
  ['m.sc'] = { 0x1D0D, 'mSC' },-- LATIN LETTER SMALL CAPITAL M
  ['n.sc'] = { 0x0274, 'nSC' },-- LATIN LETTER SMALL CAPITAL N
  ['nacute.sc'] = { 0x0274, 0x0301, 'NacuteSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING ACUTE ACCENT
  ['ncaron.sc'] = { 0x0274, 0x030C, 'NcaronSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING CARON
  ['ntilde.sc'] = { 0x0274, 0x0303, 'NtildeSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING TILDE
  ['o.sc'] = { 0x1D0F, 'oSC' },-- LATIN LETTER SMALL CAPITAL O
  ['oacute.sc'] = { 0x1D0F, 0x0301, 'OacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING ACUTE ACCENT
  ['ocircumflex.sc'] = { 0x1D0F, 0x0302, 'OcircumflexSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT
  ['odieresis.sc'] = { 0x1D0F, 0x0308, 'OdieresisSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DIAERESIS
  ['oe.sc'] = { 0x0276, 'OESC' },-- LATIN LETTER SMALL CAPITAL OE
  ['ograve.sc'] = { 0x1D0F, 0x0300, 'OgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING GRAVE ACCENT
  ['ohungarumlaut.sc'] = { 0x1D0F, 0x030B, 'OhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE ACUTE ACCENT
  ['otilde.sc'] = { 0x1D0F, 0x0303, 'OtildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING TILDE
  ['p.sc'] = { 0x1D18, 'pSC' },-- LATIN LETTER SMALL CAPITAL P
  ['q.sc'] = { 0xA7AF, 'qSC' },-- LATIN LETTER SMALL CAPITAL Q
  ['r.sc'] = { 0x0280, 'rSC' },-- LATIN LETTER SMALL CAPITAL R
  ['racute.sc'] = { 0x0280, 0x0301, 'RacuteSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING ACUTE ACCENT
  ['rcaron.sc'] = { 0x0280, 0x030C, 'RcaronSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING CARON
  ['s.sc'] = { 0xA731, 'sSC' },-- LATIN LETTER SMALL CAPITAL S
  ['sacute.sc'] = { 0xA731, 0x0301, 'SacuteSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING ACUTE ACCENT
  ['scaron.sc'] = { 0xA731, 0x030C, 'ScaronSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CARON
  ['scedilla.sc'] = { 0xA731, 0x0327, 'ScedillaSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CEDILLA
  ['scommaaccent.sc'] = { 0xA731, 0x0326, 'ScommaaccentSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING COMMA BELOW
  ['t.sc'] = { 0x1D1B, 'tSC' },-- LATIN LETTER SMALL CAPITAL T
  ['tbar.sc'] = { 0x1D1B, 0x0335, 'TbarSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING SHORT STROKE OVERLAY
  ['tcaron.sc'] = { 0x1D1B, 0x030C, 'TcaronSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CARON
  ['tcommaaccent.sc'] = { 0x1D1B, 0x0327, 'TcedillaSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CEDILLA
  ['uni021B.sc'] = { 0x1D1B, 0x0326, 'TcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING COMMA BELOW
  ['u.sc'] = { 0x1D1C, 'uSC' },-- LATIN LETTER SMALL CAPITAL U
  ['uacute.sc'] = { 0x1D1C, 0x0301, 'UacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING ACUTE ACCENT
  ['ucircumflex.sc'] = { 0x1D1C, 0x0302, 'UcircumflexSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CIRCUMFLEX ACCENT
  ['udieresis.sc'] = { 0x1D1C, 0x0308, 'UdieresisSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS
  ['ugrave.sc'] = { 0x1D1C, 0x0300, 'UgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING GRAVE ACCENT
  ['uhungarumlaut.sc'] = { 0x1D1C, 0x030B, 'UhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE ACUTE ACCENT
  ['uring.sc'] = { 0x1D1C, 0x030A, 'UringSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING RING ABOVE
  ['v.sc'] = { 0x1D20, 'vSC' },-- LATIN LETTER SMALL CAPITAL V
  ['w.sc'] = { 0x1D21, 'wSC' },-- LATIN LETTER SMALL CAPITAL W
  ['y.sc'] = { 0x028F, 'ySC' },-- LATIN LETTER SMALL CAPITAL Y
  ['yacute.sc'] = { 0x028F, 0x0301, 'YacuteSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING ACUTE ACCENT
  ['ydieresis.sc'] = { 0x028F, 0x0308, 'YdieresisSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DIAERESIS
  ['z.sc'] = { 0x1D22, 'zSC' },-- LATIN LETTER SMALL CAPITAL Z
  ['zacute.sc'] = { 0x1D22, 0x0301, 'ZacuteSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING ACUTE ACCENT
  ['zcaron.sc'] = { 0x1D22, 0x030C, 'ZcaronSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING CARON
  ['zdotaccent.sc'] = { 0x1D22, 0x0307, 'ZdotaccentSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT ABOVE
  ['kreis'] = { 0x25CB },-- WHITE CIRCLE
  ['t_z'] = { 0x0074, 0x0292, 'tezh' },-- LATIN SMALL LETTER T/LATIN SMALL LETTER EZH
  ['h.alt'] = { 0xA727 },-- LATIN SMALL LETTER HENG
  ['Tux'] = { 0x1F427 },-- PENGUIN
  ['v.alt'] = { 0x0076, 'valt1'},-- LATIN SMALL LETTER V
  ['afii10099'] = { 0x0442, 'tcyr'},-- CYRILLIC SMALL LETTER TE
  ['afii10194'] = { 0x0235, 'ncurl' },-- LATIN SMALL LETTER N WITH CURL
  ['uni1E9A'] = { 0x0251, 'latinalpha'},-- LATIN SMALL LETTER ALPHA
  ['uni1E9C.alt'] = { 0x0053, 0x0053, 'SlongSS'},-- LATIN CAPITAL LETTER S/LATIN CAPITAL LETTER S
  ['uniE00B'] = { 0x0076, 'valt'},-- LATIN SMALL LETTER V
  ['uniE00C'] = { 0x0077, 'walt'},-- LATIN SMALL LETTER W
  ['uniE00D'] = { 0x0079, 'yalt'},-- LATIN SMALL LETTER Y
  ['uniE00E'] = { 0x0475, 'izhitsa'},-- CYRILLIC SMALL LETTER IZHITSA
  ['uniE01C'] = { 0x0408, 'cyrje'},-- CYRILLIC CAPITAL LETTER JE
  ['uniE0E8'] = { 0x042F, 'Ya'},-- CYRILLIC CAPITAL LETTER YA
  ['uniE0F4'] = { 0x0292, 'ezh'},-- LATIN SMALL LETTER EZH
  ['uniE0F9'] = { 0x02BD,  0x02BD,  0x02BD, 'triplereversedcommasuperscript'},-- MODIFIER LETTER REVERSED COMMA/MODIFIER LETTER REVERSED COMMA/MODIFIER LETTER REVERSED COMMA
  ['uniE0FB'] = { 0x02BC,  0x02BC,  0x02BC, 'triplecommasuperscript'},-- MODIFIER LETTER APOSTROPHE/MODIFIER LETTER APOSTROPHE/MODIFIER LETTER APOSTROPHE
  ['uniE130'] = { 0x2043, 'hyphenbullet'},-- HYPHEN BULLET
  ['uniE138'] = { 0x1F342, 'leaf'},-- FALLEN LEAF
  ['uniE188'] = { 0x2295, 'circledplus'},-- CIRCLED PLUS
  ['uniE189'] = { 0x2296, 'circledminus'},-- CIRCLED MINUS
  ['uniF6C8'] = { 0x0442, 'cyrte'},-- CYRILLIC SMALL LETTER TE
}
