return {
  ['.notdef'] = { 0x0020 },-- SPACE
  ['exclam.sup'] = { 0xA71D, 'exclamsuperscript' },-- MODIFIER LETTER RAISED EXCLAMATION MARK
  ['parenleft.sup'] = { 0x207D, 'parenleftsuperscript' },-- SUPERSCRIPT LEFT PARENTHESIS
  ['parenright.sup'] = { 0x207E, 'parenrightsuperscript' },-- SUPERSCRIPT RIGHT PARENTHESIS
  ['plus.sup'] = { 0x207A, 'plussuperscript' },-- SUPERSCRIPT PLUS SIGN
  ['zero.sup'] = { 0x2070, 'zerosuperscript' },-- SUPERSCRIPT ZERO
  ['one.sup'] = { 0x00B9, 'onesuperscript' },-- SUPERSCRIPT ONE
  ['two.sup'] = { 0x00B2, 'twosuperscript' },-- SUPERSCRIPT TWO
  ['three.sup'] = { 0x00B3, 'threesuperscript' },-- SUPERSCRIPT THREE
  ['four.sup'] = { 0x2074, 'foursuperscript' },-- SUPERSCRIPT FOUR
  ['five.sup'] = { 0x2075, 'fivesuperscript' },-- SUPERSCRIPT FIVE
  ['six.sup'] = { 0x2076, 'sixsuperscript' },-- SUPERSCRIPT SIX
  ['seven.sup'] = { 0x2077, 'sevensuperscript' },-- SUPERSCRIPT SEVEN
  ['eight.sup'] = { 0x2078, 'eightsuperscript' },-- SUPERSCRIPT EIGHT
  ['nine.sup'] = { 0x2079, 'ninesuperscript' },-- SUPERSCRIPT NINE
  ['equal.sup'] = { 0x207C, 'equalsuperscript' },-- SUPERSCRIPT EQUALS SIGN
  ['A.sup'] = { 0x1D2C, 'Asuperscript' },-- MODIFIER LETTER CAPITAL A
  ['B.sup'] = { 0x1D2E, 'Bsuperscript' },-- MODIFIER LETTER CAPITAL B
  ['D.sup'] = { 0x1D30, 'Dsuperscript' },-- MODIFIER LETTER CAPITAL D
  ['E.sup'] = { 0x1D31, 'Esuperscript' },-- MODIFIER LETTER CAPITAL E
  ['G.sup'] = { 0x1D33, 'Gsuperscript' },-- MODIFIER LETTER CAPITAL G
  ['H.sup'] = { 0x1D34, 'Hsuperscript' },-- MODIFIER LETTER CAPITAL H
  ['I.sup'] = { 0x1D35, 'Isuperscript' },-- MODIFIER LETTER CAPITAL I
  ['J.sup'] = { 0x1D36, 'Jsuperscript' },-- MODIFIER LETTER CAPITAL J
  ['K.sup'] = { 0x1D37, 'Ksuperscript' },-- MODIFIER LETTER CAPITAL K
  ['L.sup'] = { 0x1D38, 'Lsuperscript' },-- MODIFIER LETTER CAPITAL L
  ['M.sup'] = { 0x1D39, 'Msuperscript' },-- MODIFIER LETTER CAPITAL M
  ['N.sup'] = { 0x1D3A, 'Nsuperscript' },-- MODIFIER LETTER CAPITAL N
  ['O.sup'] = { 0x1D3C, 'Osuperscript' },-- MODIFIER LETTER CAPITAL O
  ['P.sup'] = { 0x1D3E, 'Psuperscript' },-- MODIFIER LETTER CAPITAL P
  ['R.sup'] = { 0x1D3F, 'Rsuperscript' },-- MODIFIER LETTER CAPITAL R
  ['T.sup'] = { 0x1D40, 'Tsuperscript' },-- MODIFIER LETTER CAPITAL T
  ['U.sup'] = { 0x1D41, 'Usuperscript' },-- MODIFIER LETTER CAPITAL U
  ['V.sup'] = { 0x2C7D, 'Vsuperscript' },-- MODIFIER LETTER CAPITAL V
  ['W.sup'] = { 0x1D42, 'Wsuperscript' },-- MODIFIER LETTER CAPITAL W
  ['a.sup'] = { 0x1D43, 'asuperscript' },-- MODIFIER LETTER SMALL A
  ['b.sup'] = { 0x1D47, 'bsuperscript' },-- MODIFIER LETTER SMALL B
  ['c.sup'] = { 0x1D9C, 'csuperscript' },-- MODIFIER LETTER SMALL C
  ['d.sup'] = { 0x1D48, 'dsuperscript' },-- MODIFIER LETTER SMALL D
  ['e.sup'] = { 0x1D49, 'esuperscript' },-- MODIFIER LETTER SMALL E
  ['f.sup'] = { 0x1DA0, 'fsuperscript' },-- MODIFIER LETTER SMALL F
  ['g.sup'] = { 0x1D4D, 'gsuperscript' },-- MODIFIER LETTER SMALL G
  ['h.sup'] = { 0x02B0, 'hsuperscript' },-- MODIFIER LETTER SMALL H
  ['i.sup'] = { 0x2071, 'isuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['j.sup'] = { 0x02B2, 'jsuperscript' },-- MODIFIER LETTER SMALL J
  ['k.sup'] = { 0x1D4F, 'ksuperscript' },-- MODIFIER LETTER SMALL K
  ['l.sup'] = { 0x02E1, 'lsuperscript' },-- MODIFIER LETTER SMALL L
  ['m.sup'] = { 0x1D50, 'msuperscript' },-- MODIFIER LETTER SMALL M
  ['n.sup'] = { 0x207F, 'nsuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER N
  ['o.sup'] = { 0x1D52, 'osuperscript' },-- MODIFIER LETTER SMALL O
  ['p.sup'] = { 0x1D56, 'psuperscript' },-- MODIFIER LETTER SMALL P
  ['q.sup'] = { 0x107A5, 'qsuperscript' },-- MODIFIER LETTER SMALL Q
  ['r.sup'] = { 0x02B3, 'rsuperscript' },-- MODIFIER LETTER SMALL R
  ['s.sup'] = { 0x02E2, 'ssuperscript' },-- MODIFIER LETTER SMALL S
  ['t.sup'] = { 0x1D57, 'tsuperscript' },-- MODIFIER LETTER SMALL T
  ['u.sup'] = { 0x1D58, 'usuperscript' },-- MODIFIER LETTER SMALL U
  ['v.sup'] = { 0x1D5B, 'vsuperscript' },-- MODIFIER LETTER SMALL V
  ['w.sup'] = { 0x02B7, 'wsuperscript' },-- MODIFIER LETTER SMALL W
  ['x.sup'] = { 0x02E3, 'xsuperscript' },-- MODIFIER LETTER SMALL X
  ['y.sup'] = { 0x02B8, 'ysuperscript' },-- MODIFIER LETTER SMALL Y
  ['z.sup'] = { 0x1DBB, 'zsuperscript' },-- MODIFIER LETTER SMALL Z
  ['exclamdown.sup'] = { 0xA71E, 'exclamdownsuperscript' },-- MODIFIER LETTER RAISED INVERTED EXCLAMATION MARK
  ['ae.sup'] = { 0x10783, 'aesuperscript' },-- MODIFIER LETTER SMALL AE
  ['NameMe.242'] = { 0x00A7, 'sectionsups' },-- SECTION SIGN
  ['NameMe.243'] = { 0x00B6, 'pilcrowsups' },-- PILCROW SIGN
  ['NameMe.244'] = { 0x2016, 'dblbarsups' },-- DOUBLE VERTICAL LINE
  ['NameMe.245'] = { 0x2020, 'daggersups' },-- DAGGER
  ['NameMe.246'] = { 0x2021, 'ddaggersups' },-- DOUBLE DAGGER
  ['NameMe.247'] = { 0x002A, 'astsups' },-- ASTERISK
  ['NameMe.234'] = { 0x00A7, 'sectionsups1' },-- SECTION SIGN
  ['NameMe.235'] = { 0x00B6, 'pilcrowsups1' },-- PILCROW SIGN
  ['NameMe.236'] = { 0x2016, 'dblbarsups1' },-- DOUBLE VERTICAL LINE
  ['NameMe.237'] = { 0x2020, 'daggersups1' },-- DAGGER
  ['NameMe.238'] = { 0x2021, 'ddaggersups1' },-- DOUBLE DAGGER
  ['NameMe.239'] = { 0x002A, 'astsups1' },-- ASTERISK
  ['uni2017.sups'] = { 0x002A, 'asterixsuperscript' },-- ASTERISK
  ['zero.inferior'] = { 0x2080, 'zerosubscript' },-- SUBSCRIPT ZERO
  ['one.inferior'] = { 0x2081, 'onesubscript' },-- SUBSCRIPT ONE
  ['two.inferior'] = { 0x2082, 'twosubscript' },-- SUBSCRIPT TWO
  ['three.inferior'] = { 0x2083, 'threesubscript' },-- SUBSCRIPT THREE
  ['four.inferior'] = { 0x2084, 'foursubscript' },-- SUBSCRIPT FOUR
  ['five.inferior'] = { 0x2085, 'fivesubscript' },-- SUBSCRIPT FIVE
  ['six.inferior'] = { 0x2086, 'sixsubscript' },-- SUBSCRIPT SIX
  ['seven.inferior'] = { 0x2087, 'sevensubscript' },-- SUBSCRIPT SEVEN
  ['eight.inferior'] = { 0x2088, 'eightsubscript' },-- SUBSCRIPT EIGHT
  ['nine.inferior'] = { 0x2089, 'ninesubscript' },-- SUBSCRIPT NINE
}
