return {
  ['.notdef'] = { 0x0020 },-- SPACE
  ['NameMe.64.1'] = { 0x0020 },-- SPACE
  ['NameMe.53'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.54'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.55'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.56'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.57'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.58'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.59'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.60'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.61'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.62'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.63'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['NameMe.64'] = { 0x1D74F },-- MATHEMATICAL BOLD ITALIC PARTIAL DIFFERENTIAL
  ['uni2AEB.not'] = { 0x2AEB, 0x0338, 'doubleuptacknot' },-- DOUBLE UP TACK/COMBINING LONG SOLIDUS OVERLAY
}
