return {
  ['barex'] = { 0x20D3 },-- COMBINING SHORT VERTICAL LINE OVERLAY
  ['bardblex'] = { 0x20E6 },-- COMBINING DOUBLE VERTICAL STROKE OVERLAY
  ['hat4'] = { 0x02C6, 0xFE04 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/VARIATION SELECTOR-5
  ['hat5'] = { 0x02C6, 0xFE05 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/VARIATION SELECTOR-6
  ['hat6'] = { 0x02C6, 0xFE06 },-- MODIFIER LETTER CIRCUMFLEX ACCENT/VARIATION SELECTOR-7
  ['tilde4'] = { 0x02DC, 0xFE04 },-- SMALL TILDE/VARIATION SELECTOR-5
  ['tilde5'] = { 0x02DC, 0xFE05 },-- SMALL TILDE/VARIATION SELECTOR-6
  ['tilde6'] = { 0x02DC, 0xFE06 },-- SMALL TILDE/VARIATION SELECTOR-7
  ['parenlefttpA'] = { 0x239B },-- LEFT PARENTHESIS UPPER HOOK
  ['parenrighttpA'] = { 0x239E },-- RIGHT PARENTHESIS UPPER HOOK
  ['parenleftbtA'] = { 0x239D },-- LEFT PARENTHESIS LOWER HOOK
  ['parenrightbtA'] = { 0x23A0 },-- RIGHT PARENTHESIS LOWER HOOK
  ['parenleftexA'] = { 0x239C },-- LEFT PARENTHESIS EXTENSION
  ['parenrightexA'] = { 0x239F },-- RIGHT PARENTHESIS EXTENSION
  ['cupdottext.1'] = { 0x2A03, 0xFE01 },-- N-ARY UNION OPERATOR WITH DOT/VARIATION SELECTOR-2
  ['cupdotdisplay.1'] = { 0x2A03, 0xFE02 },-- N-ARY UNION OPERATOR WITH DOT/VARIATION SELECTOR-3
  ['cupdottext'] = { 0x2A03, 0xFE01 },-- N-ARY UNION OPERATOR WITH DOT/VARIATION SELECTOR-2
  ['cupdotdisplay'] = { 0x2A03, 0xFE02 },-- N-ARY UNION OPERATOR WITH DOT/VARIATION SELECTOR-3
  }
