return {
  ['.notdef'] = { 0x0020 },-- SPACE
  ['A.superior.alt'] = { 0x1D2C, 'Asuperscript' },-- MODIFIER LETTER CAPITAL A
  ['A.sups'] = { 0x1D2C, 'Asups' },-- MODIFIER LETTER CAPITAL A
  ['Aogonekacute'] = { 0x00C1, 0x0328 },-- LATIN CAPITAL LETTER A WITH ACUTE/COMBINING OGONEK
  ['B.superior.alt'] = { 0x1D2E, 'Bsuperscript' },-- MODIFIER LETTER CAPITAL B
  ['B.sups'] = { 0x1D2E, 'Bsups' },-- MODIFIER LETTER CAPITAL B
  ['D.superior.alt'] = { 0x1D30, 'Dsuperscript' },-- MODIFIER LETTER CAPITAL D
  ['D.sups'] = { 0x1D30, 'Dsups' },-- MODIFIER LETTER CAPITAL D
  ['E.superior.alt'] = { 0x1D31, 'Esuperscript' },-- MODIFIER LETTER CAPITAL E
  ['E.sups'] = { 0x1D31, 'Esups' },-- MODIFIER LETTER CAPITAL E
  ['Eogonekacute'] = { 0x00C9, 0x0328 },-- LATIN CAPITAL LETTER E WITH ACUTE/COMBINING OGONEK
  ['G.superior.alt'] = { 0x1D33, 'Gsuperscript' },-- MODIFIER LETTER CAPITAL G
  ['G.sups'] = { 0x1D33, 'Gsups' },-- MODIFIER LETTER CAPITAL G
  ['Germandbls'] = { 0x0053, 0x0053, 'GermandblsSS' },-- LATIN CAPITAL LETTER S/LATIN CAPITAL LETTER S
  ['H.superior.alt'] = { 0x1D34, 'Hsuperscript' },-- MODIFIER LETTER CAPITAL H
  ['H.sups'] = { 0x1D34, 'Hsups' },-- MODIFIER LETTER CAPITAL H
  ['I.superior.alt'] = { 0x1D35, 'Isuperscript' },-- MODIFIER LETTER CAPITAL I
  ['I.sups'] = { 0x1D35, 'Isups' },-- MODIFIER LETTER CAPITAL I
  ['Iogonekacute'] = { 0x00CD, 0x0328 },-- LATIN CAPITAL LETTER I WITH ACUTE/COMBINING OGONEK
  ['J.superior.alt'] = { 0x1D36, 'Jsuperscript' },-- MODIFIER LETTER CAPITAL J
  ['J.sups'] = { 0x1D36, 'Jsups' },-- MODIFIER LETTER CAPITAL J
  ['J_uni030C.cap'] = { 0x004A, 0x0315, 'Jcaronalt'},-- LATIN CAPITAL LETTER J/COMBINING COMMA ABOVE RIGHT
  ['Jacute'] = { 0x004A, 0x0301 },-- LATIN CAPITAL LETTER J/COMBINING ACUTE ACCENT
  ['K.superior.alt'] = { 0x1D37, 'Ksuperscript' },-- MODIFIER LETTER CAPITAL K
  ['K.sups'] = { 0x1D37, 'Ksups' },-- MODIFIER LETTER CAPITAL K
  ['L.superior.alt'] = { 0x1D38, 'Lsuperscript' },-- MODIFIER LETTER CAPITAL L
  ['L.sups'] = { 0x1D38, 'Lsups' },-- MODIFIER LETTER CAPITAL L
  ['M.superior.alt'] = { 0x1D39, 'Msuperscript' },-- MODIFIER LETTER CAPITAL M
  ['M.sups'] = { 0x1D39, 'Msups' },-- MODIFIER LETTER CAPITAL M
  ['N.superior.alt'] = { 0x1D3A, 'Nsuperscript' },-- MODIFIER LETTER CAPITAL N
  ['N.sups'] = { 0x1D3A, 'Nsups' },-- MODIFIER LETTER CAPITAL N
  ['O.superior.alt'] = { 0x1D3C, 'Osuperscript' },-- MODIFIER LETTER CAPITAL O
  ['O.sups'] = { 0x1D3C, 'Osups' },-- MODIFIER LETTER CAPITAL O
  ['Oogonekacute'] = { 0x01EA, 0x0301 },-- LATIN CAPITAL LETTER O WITH OGONEK/COMBINING ACUTE ACCENT
  ['Orogate'] = { 0xA7C0 },-- LATIN CAPITAL LETTER OLD POLISH O
  ['P.superior.alt'] = { 0x1D3E, 'Psuperscript' },-- MODIFIER LETTER CAPITAL P
  ['P.sups'] = { 0x1D3E, 'Psups' },-- MODIFIER LETTER CAPITAL P
  ['R.superior.alt'] = { 0x1D3F, 'Rsuperscript' },-- MODIFIER LETTER CAPITAL R
  ['R.sups'] = { 0x1D3F, 'Rsups' },-- MODIFIER LETTER CAPITAL R
  ['T.superior.alt'] = { 0x1D40, 'Tsuperscript' },-- MODIFIER LETTER CAPITAL T
  ['T.sups'] = { 0x1D40, 'Tsups' },-- MODIFIER LETTER CAPITAL T
  ['U.superior.alt'] = { 0x1D41, 'Usuperscript' },-- MODIFIER LETTER CAPITAL U
  ['U.sups'] = { 0x1D41, 'Usups' },-- MODIFIER LETTER CAPITAL U
  ['V.superior.alt'] = { 0x2C7D, 'Vsuperscript' },-- MODIFIER LETTER CAPITAL V
  ['V.sups'] = { 0x2C7D, 'Vsups' },-- MODIFIER LETTER CAPITAL V
  ['W.superior.alt'] = { 0x1D42, 'Wsuperscript' },-- MODIFIER LETTER CAPITAL W
  ['W.sups'] = { 0x1D42, 'Wsups' },-- MODIFIER LETTER CAPITAL W
  ['a.pc'] = { 0x1D00, 'aPC' },-- LATIN LETTER SMALL CAPITAL A
  ['a.sc'] = { 0x1D00, 'aSC' },-- LATIN LETTER SMALL CAPITAL A
  ['a.superior.alt'] = { 0x1D43, 'asuperscript' },-- MODIFIER LETTER SMALL A
  ['a.sups'] = { 0x1D43, 'asups' },-- MODIFIER LETTER SMALL A
  ['aacute.pc'] = { 0x1D00, 0x0301, 'AacutePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING ACUTE ACCENT
  ['aacute.sc'] = { 0x1D00, 0x0301, 'AacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING ACUTE ACCENT
  ['abreve.pc'] = { 0x1D00, 0x0306, 'AbrevePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE
  ['abreve.sc'] = { 0x1D00, 0x0306, 'AbreveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE
  ['abreveacute.pc'] = { 0x1D00, 0x0306, 0x0301, 'AbreveacutePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING ACUTE ACCENT
  ['abreveacute.sc'] = { 0x1D00, 0x0306, 0x0301, 'AbreveacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING ACUTE ACCENT
  ['abrevedotbelow.pc'] = { 0x1D00, 0x0306, 0x0323, 'AbrevedotbelowPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING DOT BELOW
  ['abrevedotbelow.sc'] = { 0x1D00, 0x0306, 0x0323, 'AbrevedotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING DOT BELOW
  ['abrevegrave.pc'] = { 0x1D00, 0x0306, 0x0300, 'AbrevegravePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING GRAVE ACCENT
  ['abrevegrave.sc'] = { 0x1D00, 0x0306, 0x0300, 'AbrevegraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING GRAVE ACCENT
  ['abrevehookabove.pc'] = { 0x1D00, 0x0306, 0x0309, 'AbrevehookabovePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING HOOK ABOVE
  ['abrevehookabove.sc'] = { 0x1D00, 0x0306, 0x0309, 'AbrevehookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING HOOK ABOVE
  ['abrevetilde.pc'] = { 0x1D00, 0x0306, 0x0303, 'AbrevetildePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING TILDE
  ['abrevetilde.sc'] = { 0x1D00, 0x0306, 0x0303, 'AbrevetildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING BREVE/COMBINING TILDE
  ['acaron.pc'] = { 0x1D00, 0x030C, 'AcaronPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CARON
  ['acaron.sc'] = { 0x1D00, 0x030C, 'AcaronSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CARON
  ['acircumflex.pc'] = { 0x1D00, 0x0302, 'AcircumflexPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT
  ['acircumflex.sc'] = { 0x1D00, 0x0302, 'AcircumflexSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT
  ['acircumflexacute.pc'] = { 0x1D00, 0x0302, 0x0301, 'AcircumflexacutePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['acircumflexacute.sc'] = { 0x1D00, 0x0302, 0x0301, 'AcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['acircumflexdotbelow.pc'] = { 0x1D00, 0x0302, 0x0323, 'AcircumflexdotbelowPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['acircumflexdotbelow.sc'] = { 0x1D00, 0x0302, 0x0323, 'AcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['acircumflexgrave.pc'] = { 0x1D00, 0x0302, 0x0300, 'AcircumflexgravePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['acircumflexgrave.sc'] = { 0x1D00, 0x0302, 0x0300, 'AcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['acircumflexhookabove.pc'] = { 0x1D00, 0x0302, 0x0309, 'AcircumflexhookabovePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['acircumflexhookabove.sc'] = { 0x1D00, 0x0302, 0x0309, 'AcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['acircumflextilde.pc'] = { 0x1D00, 0x0302, 0x0303, 'AcircumflextildePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['acircumflextilde.sc'] = { 0x1D00, 0x0302, 0x0303, 'AcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['adblgrave.pc'] = { 0x1D00, 0x030F, 'AdblgravePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOUBLE GRAVE ACCENT
  ['adblgrave.sc'] = { 0x1D00, 0x030F, 'AdblgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOUBLE GRAVE ACCENT
  ['adieresis.pc'] = { 0x1D00, 0x0308, 'AdieresisPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DIAERESIS
  ['adieresis.sc'] = { 0x1D00, 0x0308, 'AdieresisSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DIAERESIS
  ['adotbelow.pc'] = { 0x1D00, 0x0323, 'AdotbelowPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOT BELOW
  ['adotbelow.sc'] = { 0x1D00, 0x0323, 'AdotbelowSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING DOT BELOW
  ['ae.pc'] = { 0x1D01, 'AEPC' },-- LATIN LETTER SMALL CAPITAL AE
  ['ae.sc'] = { 0x1D01, 'AESC' },-- LATIN LETTER SMALL CAPITAL AE
  ['ae.superior.alt'] = { 0x10783, 'aesuperscript' },-- MODIFIER LETTER SMALL AE
  ['aeacute.pc'] = { 0x1D01, 0x0301, 'AEacutePC' },-- LATIN LETTER SMALL CAPITAL AE/COMBINING ACUTE ACCENT
  ['aeacute.sc'] = { 0x1D01, 0x0301, 'AEacuteSC' },-- LATIN LETTER SMALL CAPITAL AE/COMBINING ACUTE ACCENT
  ['agrave.pc'] = { 0x1D00, 0x0300, 'AgravePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING GRAVE ACCENT
  ['agrave.sc'] = { 0x1D00, 0x0300, 'AgraveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING GRAVE ACCENT
  ['ahookabove.pc'] = { 0x1D00, 0x0309, 'AhookabovePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING HOOK ABOVE
  ['ahookabove.sc'] = { 0x1D00, 0x0309, 'AhookaboveSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING HOOK ABOVE
  ['amacron.pc'] = { 0x1D00, 0x0304, 'AmacronPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING MACRON
  ['amacron.sc'] = { 0x1D00, 0x0304, 'AmacronSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING MACRON
  ['anglearc'] = { 0x2222 },-- SPHERICAL ANGLE
  ['aogonek.pc'] = { 0x1D00, 0x0328, 'AogonekPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK
  ['aogonek.sc'] = { 0x1D00, 0x0328, 'AogonekSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK
  ['aogonekacute'] = { 0x0105, 0x0301 },-- LATIN SMALL LETTER A WITH OGONEK/COMBINING ACUTE ACCENT
  ['aogonekacute.pc'] = { 0x1D00, 0x0328, 0x0301, 'AogonekacutePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['aogonekacute.sc'] = { 0x1D00, 0x0328, 0x0301, 'AogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['aring.pc'] = { 0x1D00, 0x030A, 'AringPC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE
  ['aring.sc'] = { 0x1D00, 0x030A, 'AringSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE
  ['aringacute.pc'] = { 0x1D00, 0x030A, 0x0301, 'AringacutePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE/COMBINING ACUTE ACCENT
  ['aringacute.sc'] = { 0x1D00, 0x030A, 0x0301, 'AringacuteSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING RING ABOVE/COMBINING ACUTE ACCENT
  ['atilde.pc'] = { 0x1D00, 0x0303, 'AtildePC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING TILDE
  ['atilde.sc'] = { 0x1D00, 0x0303, 'AtildeSC' },-- LATIN LETTER SMALL CAPITAL A/COMBINING TILDE
  ['b.pc'] = { 0x0299, 'bPC' },-- LATIN LETTER SMALL CAPITAL B
  ['b.sc'] = { 0x0299, 'bSC' },-- LATIN LETTER SMALL CAPITAL B
  ['b.superior.alt'] = { 0x1D47, 'bsuperscript' },-- MODIFIER LETTER SMALL B
  ['b.sups'] = { 0x1D47, 'bsups' },-- MODIFIER LETTER SMALL B
  ['baht'] = { 0x0E3F },-- THAI CURRENCY SYMBOL BAHT
  ['bigcircle'] = { 0x25EF },-- LARGE CIRCLE
  ['blanksymbol'] = { 0x2422 },-- BLANK SYMBOL
  ['c.pc'] = { 0x1D04, 'cPC' },-- LATIN LETTER SMALL CAPITAL C
  ['c.sc'] = { 0x1D04, 'cSC' },-- LATIN LETTER SMALL CAPITAL C
  ['c.superior.alt'] = { 0x1D9C, 'csuperscript' },-- MODIFIER LETTER SMALL C
  ['c.sups'] = { 0x1D9C, 'csups' },-- MODIFIER LETTER SMALL C
  ['cacute.pc'] = { 0x1D04, 0x0301, 'CacutePC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING ACUTE ACCENT
  ['cacute.sc'] = { 0x1D04, 0x0301, 'CacuteSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING ACUTE ACCENT
  ['ccaron.pc'] = { 0x1D04, 0x030C, 'CcaronPC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CARON
  ['ccaron.sc'] = { 0x1D04, 0x030C, 'CcaronSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CARON
  ['ccedilla.pc'] = { 0x1D04, 0x0327, 'CcedillaPC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CEDILLA
  ['ccedilla.sc'] = { 0x1D04, 0x0327, 'CcedillaSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CEDILLA
  ['ccircumflex.pc'] = { 0x1D04, 0x0302, 'CcircumflexPC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CIRCUMFLEX ACCENT
  ['ccircumflex.sc'] = { 0x1D04, 0x0302, 'CcircumflexSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING CIRCUMFLEX ACCENT
  ['cdotaccent.pc'] = { 0x1D04, 0x0307, 'CdotaccentPC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING DOT ABOVE
  ['cdotaccent.sc'] = { 0x1D04, 0x0307, 'CdotaccentSC' },-- LATIN LETTER SMALL CAPITAL C/COMBINING DOT ABOVE
  ['copyleft'] = { 0x1F12F },-- COPYLEFT SYMBOL
  ['cwmascender'] = { 0x200C },-- ZERO WIDTH NON-JOINER
  ['cwmcapital'] = { 0x200C },-- ZERO WIDTH NON-JOINER
  ['d.pc'] = { 0x1D05, 'dPC' },-- LATIN LETTER SMALL CAPITAL D
  ['d.sc'] = { 0x1D05, 'dSC' },-- LATIN LETTER SMALL CAPITAL D
  ['d.superior.alt'] = { 0x1D48, 'dsuperscript' },-- MODIFIER LETTER SMALL D
  ['d.sups'] = { 0x1D48, 'dsups' },-- MODIFIER LETTER SMALL D
  ['dblgrave.ts1'] = { 0x030F, 'dblgravecmb' },-- COMBINING DOUBLE GRAVE ACCENT
  ['dcaron.pc'] = { 0x1D05, 0x030C, 'DcaronPC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING CARON
  ['dcaron.sc'] = { 0x1D05, 0x030C, 'DcaronSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING CARON
  ['dcroat.pc'] = { 0x1D05, 0x0335, 'DcroatPC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING SHORT STROKE OVERLAY
  ['dcroat.sc'] = { 0x1D05, 0x0335, 'DcroatSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING SHORT STROKE OVERLAY
  ['ddotbelow.pc'] = { 0x1D05, 0x0323, 'DdotbelowPC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING DOT BELOW
  ['ddotbelow.sc'] = { 0x1D05, 0x0323, 'DdotbelowSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING DOT BELOW
  ['diameter'] = { 0x2300 },-- DIAMETER SIGN
  ['died'] = { 0x271D },-- LATIN CROSS
  ['discount'] = { 0x2052 },-- COMMERCIAL MINUS SIGN
  ['divorced'] = { 0x26AE },-- DIVORCE SYMBOL
  ['dlinebelow.pc'] = { 0x1D05, 0x0331, 'DlinebelowPC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING MACRON BELOW
  ['dlinebelow.sc'] = { 0x1D05, 0x0331, 'DlinebelowSC' },-- LATIN LETTER SMALL CAPITAL D/COMBINING MACRON BELOW
  ['dotlessi.pc'] = { 0x026A, 'IdotlesPC' },-- LATIN LETTER SMALL CAPITAL I
  ['dotlessi.sc'] = { 0x026A, 'IdotlesSC' },-- LATIN LETTER SMALL CAPITAL I
  ['dotlessj'] = { 0x0237 },-- LATIN SMALL LETTER DOTLESS J
  ['dotlessj.pc'] = { 0x1D0A, 'JdotlessPC' },-- LATIN LETTER SMALL CAPITAL J
  ['dotlessj.sc'] = { 0x1D0A, 'JdotlessSC' },-- LATIN LETTER SMALL CAPITAL J
  ['e.pc'] = { 0x1D07, 'ePC' },-- LATIN LETTER SMALL CAPITAL E
  ['e.sc'] = { 0x1D07, 'eSC' },-- LATIN LETTER SMALL CAPITAL E
  ['e.superior.alt'] = { 0x1D49, 'esuperscript' },-- MODIFIER LETTER SMALL E
  ['e.sups'] = { 0x1D49, 'esups' },-- MODIFIER LETTER SMALL E
  ['eacute.pc'] = { 0x1D07, 0x0301, 'EacutePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING ACUTE ACCENT
  ['eacute.sc'] = { 0x1D07, 0x0301, 'EacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING ACUTE ACCENT
  ['ebreve.pc'] = { 0x1D07, 0x0306, 'EbrevePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING BREVE
  ['ebreve.sc'] = { 0x1D07, 0x0306, 'EbreveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING BREVE
  ['ecaron.pc'] = { 0x1D07, 0x030C, 'EcaronPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CARON
  ['ecaron.sc'] = { 0x1D07, 0x030C, 'EcaronSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CARON
  ['ecircumflex.pc'] = { 0x1D07, 0x0302, 'EcircumflexPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT
  ['ecircumflex.sc'] = { 0x1D07, 0x0302, 'EcircumflexSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT
  ['ecircumflexacute.pc'] = { 0x1D07, 0x0302, 0x0301, 'EcircumflexacutePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ecircumflexacute.sc'] = { 0x1D07, 0x0302, 0x0301, 'EcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ecircumflexdotbelow.pc'] = { 0x1D07, 0x0302, 0x0323, 'EcircumflexdotbelowPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ecircumflexdotbelow.sc'] = { 0x1D07, 0x0302, 0x0323, 'EcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ecircumflexgrave.pc'] = { 0x1D07, 0x0302, 0x0300, 'EcircumflexgravePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ecircumflexgrave.sc'] = { 0x1D07, 0x0302, 0x0300, 'EcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ecircumflexhookabove.pc'] = { 0x1D07, 0x0302, 0x0309, 'EcircumflexhookabovePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ecircumflexhookabove.sc'] = { 0x1D07, 0x0302, 0x0309, 'EcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ecircumflextilde.pc'] = { 0x1D07, 0x0302, 0x0303, 'EcircumflextildePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['ecircumflextilde.sc'] = { 0x1D07, 0x0302, 0x0303, 'EcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['edblgrave.pc'] = { 0x1D07, 0x030F, 'EdblgravePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOUBLE GRAVE ACCENT
  ['edblgrave.sc'] = { 0x1D07, 0x030F, 'EdblgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOUBLE GRAVE ACCENT
  ['edieresis.pc'] = { 0x1D07, 0x0308, 'EdieresisPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DIAERESIS
  ['edieresis.sc'] = { 0x1D07, 0x0308, 'EdieresisSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DIAERESIS
  ['edotaccent.pc'] = { 0x1D07, 0x0307, 'EdotaccentPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT ABOVE
  ['edotaccent.sc'] = { 0x1D07, 0x0307, 'EdotaccentSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT ABOVE
  ['edotbelow.pc'] = { 0x1D07, 0x0323, 'EdotbelowPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT BELOW
  ['edotbelow.sc'] = { 0x1D07, 0x0323, 'EdotbelowSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING DOT BELOW
  ['egrave.pc'] = { 0x1D07, 0x0300, 'EgravePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING GRAVE ACCENT
  ['egrave.sc'] = { 0x1D07, 0x0300, 'EgraveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING GRAVE ACCENT
  ['ehookabove.pc'] = { 0x1D07, 0x0309, 'EhookabovePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING HOOK ABOVE
  ['ehookabove.sc'] = { 0x1D07, 0x0309, 'EhookaboveSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING HOOK ABOVE
  ['eight.inferior'] = { 0x2088, 'eightsubscript' },-- SUBSCRIPT EIGHT
  ['eight.inferior.alt'] = { 0x2088, 'eightsubscriptalt' },-- SUBSCRIPT EIGHT
  ['eight.superior.alt'] = { 0x2078, 'eightsuperscript' },-- SUPERSCRIPT EIGHT
  ['eight.sups'] = { 0x2078, 'eightsups' },-- SUPERSCRIPT EIGHT
  ['emacron.pc'] = { 0x1D07, 0x0304, 'EmacronPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING MACRON
  ['emacron.sc'] = { 0x1D07, 0x0304, 'EmacronSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING MACRON
  ['eogonek.pc'] = { 0x1D07, 0x0328, 'EogonekPC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK
  ['eogonek.sc'] = { 0x1D07, 0x0328, 'EogonekSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK
  ['eogonekacute'] = { 0x0119, 0x0301 },-- LATIN SMALL LETTER E WITH OGONEK/COMBINING ACUTE ACCENT
  ['eogonekacute.pc'] = { 0x1D07, 0x0328, 0x0301, 'EogonekacutePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['eogonekacute.sc'] = { 0x1D07, 0x0328, 0x0301, 'EogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['equal.superior.alt'] = { 0x207C, 'equalsuperscript' },-- SUPERSCRIPT EQUALS SIGN
  ['equal.sups'] = { 0x207C, 'equalsups' },-- SUPERSCRIPT EQUALS SIGN
  ['ereversed.pc'] = { 0x2C7B, 'EreversedPC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['ereversed.sc'] = { 0x2C7B, 'EreversedSC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['eth.pc'] = { 0x1D06, 'ethPC' },-- LATIN LETTER SMALL CAPITAL ETH
  ['eth.sc'] = { 0x1D06, 'ethSC' },-- LATIN LETTER SMALL CAPITAL ETH
  ['etilde.pc'] = { 0x1D07, 0x0303, 'EtildePC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING TILDE
  ['etilde.sc'] = { 0x1D07, 0x0303, 'EtildeSC' },-- LATIN LETTER SMALL CAPITAL E/COMBINING TILDE
  ['eturned.pc'] = { 0x2C7B, 'EturnedPC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['eturned.sc'] = { 0x2C7B, 'EturnedSC' },-- LATIN LETTER SMALL CAPITAL TURNED E
  ['exclam.superior.alt'] = { 0xA71D, 'exclamsuperscript' },-- MODIFIER LETTER RAISED EXCLAMATION MARK
  ['exclam.sups'] = { 0xA71D, 'exclamsups' },-- MODIFIER LETTER RAISED EXCLAMATION MARK
  ['f.pc'] = { 0xA730, 'fPC' },-- LATIN LETTER SMALL CAPITAL F
  ['f.sc'] = { 0xA730, 'fSC' },-- LATIN LETTER SMALL CAPITAL F
  ['f.superior.alt'] = { 0x1DA0, 'fsuperscript' },-- MODIFIER LETTER SMALL F
  ['f.sups'] = { 0x1DA0, 'fsups' },-- MODIFIER LETTER SMALL F
  ['five.inferior'] = { 0x2085, 'fivesubscript' },-- SUBSCRIPT FIVE
  ['five.inferior.alt'] = { 0x2085, 'fivesubscriptalt' },-- SUBSCRIPT FIVE
  ['five.superior.alt'] = { 0x2075, 'fivesuperscript' },-- SUPERSCRIPT FIVE
  ['five.sups'] = { 0x2075, 'fivesups' },-- SUPERSCRIPT FIVE
  ['four.inferior'] = { 0x2084, 'foursubscript' },-- SUBSCRIPT FOUR
  ['four.inferior.alt'] = { 0x2084, 'foursubscriptalt' },-- SUBSCRIPT FOUR
  ['four.superior.alt'] = { 0x2074, 'foursuperscript' },-- SUPERSCRIPT FOUR
  ['four.sups'] = { 0x2074, 'foursups' },-- SUPERSCRIPT FOUR
  ['g.pc'] = { 0x0262, 'gPC' },-- LATIN LETTER SMALL CAPITAL G
  ['g.sc'] = { 0x0262, 'gSC' },-- LATIN LETTER SMALL CAPITAL G
  ['g.superior.alt'] = { 0x1D4D, 'gsuperscript' },-- MODIFIER LETTER SMALL G
  ['g.sups'] = { 0x1D4D, 'gsups' },-- MODIFIER LETTER SMALL G
  ['gacute.pc'] = { 0x0262, 0x0301, 'GacutePC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING ACUTE ACCENT
  ['gacute.sc'] = { 0x0262, 0x0301, 'GacuteSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING ACUTE ACCENT
  ['gbreve.pc'] = { 0x0262, 0x0306, 'GbrevePC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING BREVE
  ['gbreve.sc'] = { 0x0262, 0x0306, 'GbreveSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING BREVE
  ['gcaron.pc'] = { 0x0262, 0x030C, 'GcaronPC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CARON
  ['gcaron.sc'] = { 0x0262, 0x030C, 'GcaronSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CARON
  ['gcircumflex.pc'] = { 0x0262, 0x0302, 'GcircumflexPC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CIRCUMFLEX ACCENT
  ['gcircumflex.sc'] = { 0x0262, 0x0302, 'GcircumflexSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING CIRCUMFLEX ACCENT
  ['gcommaaccent.pc'] = { 0x0262, 0x0326, 'GPC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING COMMA BELOW
  ['gcommaaccent.sc'] = { 0x0262, 0x0326, 'GSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING COMMA BELOW
  ['gdotaccent.pc'] = { 0x0262, 0x0307, 'GdotaccentPC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING DOT ABOVE
  ['gdotaccent.sc'] = { 0x0262, 0x0307, 'GdotaccentSC' },-- LATIN LETTER SMALL CAPITAL G/COMBINING DOT ABOVE
  ['gnaborretni'] = { 0x2E18 },-- INVERTED INTERROBANG
  ['greaterequal.slant'] = { 0x2A7E, 'greaterequalslant' },-- GREATER-THAN OR SLANTED EQUAL TO
  ['guarani'] = { 0x20B2 },-- GUARANI SIGN
  ['h.pc'] = { 0x029C, 'hPC' },-- LATIN LETTER SMALL CAPITAL H
  ['h.sc'] = { 0x029C, 'hSC' },-- LATIN LETTER SMALL CAPITAL H
  ['h.superior.alt'] = { 0x02B0, 'hsuperscript' },-- MODIFIER LETTER SMALL H
  ['h.sups'] = { 0x02B0, 'hsups' },-- MODIFIER LETTER SMALL H
  ['h_uni0303.pc'] = { 0x029C, 0x0303, 'HtildePC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING TILDE
  ['h_uni0303.sc'] = { 0x029C, 0x0303, 'HtildeSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING TILDE
  ['hbar.pc'] = { 0x029C, 0x0336, 'HbarPC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING LONG STROKE OVERLAY
  ['hbar.sc'] = { 0x029C, 0x0336, 'HbarSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING LONG STROKE OVERLAY
  ['hbrevebelow.pc'] = { 0x029C, 0x032E, 'HbrevebelowPC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING BREVE BELOW
  ['hbrevebelow.sc'] = { 0x029C, 0x032E, 'HbrevebelowSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING BREVE BELOW
  ['hcircumflex.pc'] = { 0x029C, 0x0302, 'HcircumflexPC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING CIRCUMFLEX ACCENT
  ['hcircumflex.sc'] = { 0x029C, 0x0302, 'HcircumflexSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING CIRCUMFLEX ACCENT
  ['hdieresis.pc'] = { 0x029C, 0x0308, 'HdieresisPC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DIAERESIS
  ['hdieresis.sc'] = { 0x029C, 0x0308, 'HdieresisSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DIAERESIS
  ['hdotbelow.pc'] = { 0x029C, 0x0323, 'HdotbelowPC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DOT BELOW
  ['hdotbelow.sc'] = { 0x029C, 0x0323, 'HdotbelowSC' },-- LATIN LETTER SMALL CAPITAL H/COMBINING DOT BELOW
  ['hyphen.sups'] = { 0x207B, 'hyphensups' },-- SUPERSCRIPT MINUS
  ['hyphendbl'] = { 0x2E40 },-- DOUBLE HYPHEN
  ['hyphendbl.alt'] = { 0x2E40 },-- DOUBLE HYPHEN
  ['i.pc'] = { 0x026A, 'iPC' },-- LATIN LETTER SMALL CAPITAL I
  ['i.sc'] = { 0x026A, 'iSC' },-- LATIN LETTER SMALL CAPITAL I
  ['i.superior.alt'] = { 0x2071, 'isuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['i.sups'] = { 0x2071, 'isups' },-- SUPERSCRIPT LATIN SMALL LETTER I
  ['iacute.pc'] = { 0x026A, 0x0301, 'IacutePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING ACUTE ACCENT
  ['iacute.sc'] = { 0x026A, 0x0301, 'IacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING ACUTE ACCENT
  ['ibreve.pc'] = { 0x026A, 0x0306, 'IbrevePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING BREVE
  ['ibreve.sc'] = { 0x026A, 0x0306, 'IbreveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING BREVE
  ['icaron.pc'] = { 0x026A, 0x030C, 'IcaronPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CARON
  ['icaron.sc'] = { 0x026A, 0x030C, 'IcaronSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CARON
  ['icircumflex.pc'] = { 0x026A, 0x0302, 'IcircumflexPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CIRCUMFLEX ACCENT
  ['icircumflex.sc'] = { 0x026A, 0x0302, 'IcircumflexSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING CIRCUMFLEX ACCENT
  ['idblgrave.pc'] = { 0x026A, 0x030F, 'IdblgravePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOUBLE GRAVE ACCENT
  ['idblgrave.sc'] = { 0x026A, 0x030F, 'IdblgraveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOUBLE GRAVE ACCENT
  ['idieresis.pc'] = { 0x026A, 0x0308, 'IdieresisPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS
  ['idieresis.sc'] = { 0x026A, 0x0308, 'IdieresisSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS
  ['idieresisacute.pc'] = { 0x026A, 0x0308, 0x0301, 'IdieresisacutePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['idieresisacute.sc'] = { 0x026A, 0x0308, 0x0301, 'IdieresisacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['idotaccent.pc'] = { 0x026A, 0x0307, 'IdotaccentPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT ABOVE
  ['idotaccent.sc'] = { 0x026A, 0x0307, 'IdotaccentSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT ABOVE
  ['idotbelow.pc'] = { 0x026A, 0x0323, 'IdotbelowPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT BELOW
  ['idotbelow.sc'] = { 0x026A, 0x0323, 'IdotbelowSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING DOT BELOW
  ['igrave.pc'] = { 0x026A, 0x0300, 'IgravePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING GRAVE ACCENT
  ['igrave.sc'] = { 0x026A, 0x0300, 'IgraveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING GRAVE ACCENT
  ['ihookabove.pc'] = { 0x026A, 0x0309, 'IhookabovePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING HOOK ABOVE
  ['ihookabove.sc'] = { 0x026A, 0x0309, 'IhookaboveSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING HOOK ABOVE
  ['ij.pc'] = { 0x026A, 0x1D0A, 'ijPC' },-- LATIN LETTER SMALL CAPITAL I/LATIN LETTER SMALL CAPITAL J
  ['ij.sc'] = { 0x026A, 0x1D0A, 'ijSC' },-- LATIN LETTER SMALL CAPITAL I/LATIN LETTER SMALL CAPITAL J
  ['imacron.alt.pc'] = { 0x026A, 0x0304, 'ImacronaltPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['imacron.alt.sc'] = { 0x026A, 0x0304, 'ImacronaltSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['imacron.pc'] = { 0x026A, 0x0304, 'ImacronPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['imacron.sc'] = { 0x026A, 0x0304, 'ImacronSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING MACRON
  ['iogonek.pc'] = { 0x026A, 0x0328, 'IogonekPC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK
  ['iogonek.sc'] = { 0x026A, 0x0328, 'IogonekSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK
  ['iogonekacute'] = { 0x00ED, 0x0328 },-- LATIN SMALL LETTER I WITH ACUTE/COMBINING OGONEK
  ['iogonekacute.pc'] = { 0x026A, 0x0328, 0x0301, 'IogonekacutePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['iogonekacute.sc'] = { 0x026A, 0x0328, 0x0301, 'IogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['itilde.pc'] = { 0x026A, 0x0303, 'ItildePC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING TILDE
  ['itilde.sc'] = { 0x026A, 0x0303, 'ItildeSC' },-- LATIN LETTER SMALL CAPITAL I/COMBINING TILDE
  ['j.pc'] = { 0x1D0A, 'jPC' },-- LATIN LETTER SMALL CAPITAL J
  ['j.sc'] = { 0x1D0A, 'jSC' },-- LATIN LETTER SMALL CAPITAL J
  ['j.superior.alt'] = { 0x02B2, 'jsuperscript' },-- MODIFIER LETTER SMALL J
  ['j.sups'] = { 0x02B2, 'jsups' },-- MODIFIER LETTER SMALL J
  ['jacute'] = { 0x0237, 0x0301 },-- LATIN SMALL LETTER DOTLESS J/COMBINING ACUTE ACCENT
  ['jacute.pc'] = { 0x1D0A, 0x0301, 'JacutePC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING ACUTE ACCENT
  ['jacute.sc'] = { 0x1D0A, 0x0301, 'JacuteSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING ACUTE ACCENT
  ['jcaron.pc'] = { 0x1D0A, 0x030C, 'JcaronPC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CARON
  ['jcaron.sc'] = { 0x1D0A, 0x030C, 'JcaronSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CARON
  ['jcircumflex.pc'] = { 0x1D0A, 0x0302, 'JcircumflexPC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CIRCUMFLEX ACCENT
  ['jcircumflex.sc'] = { 0x1D0A, 0x0302, 'JcircumflexSC' },-- LATIN LETTER SMALL CAPITAL J/COMBINING CIRCUMFLEX ACCENT
  ['k.pc'] = { 0x1D0B, 'kPC' },-- LATIN LETTER SMALL CAPITAL K
  ['k.sc'] = { 0x1D0B, 'kSC' },-- LATIN LETTER SMALL CAPITAL K
  ['k.superior.alt'] = { 0x1D4F, 'ksuperscript' },-- MODIFIER LETTER SMALL K
  ['k.sups'] = { 0x1D4F, 'ksups' },-- MODIFIER LETTER SMALL K
  ['kcommaaccent.pc'] = { 0x1D0B, 0x0326, 'KcommaaccentPC' },-- LATIN LETTER SMALL CAPITAL K/COMBINING COMMA BELOW
  ['kcommaaccent.sc'] = { 0x1D0B, 0x0326, 'KcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL K/COMBINING COMMA BELOW
  ['l.pc'] = { 0x029F, 'lPC' },-- LATIN LETTER SMALL CAPITAL L
  ['l.sc'] = { 0x029F, 'lSC' },-- LATIN LETTER SMALL CAPITAL L
  ['l.script'] = { 0x2113, 'lscript'},-- SCRIPT SMALL L
  ['l.script.dup'] = { 0x2113, 'lscriptdup' },-- SCRIPT SMALL L
  ['l.superior.alt'] = { 0x02E1, 'lsuperscript' },-- MODIFIER LETTER SMALL L
  ['l.sups'] = { 0x02E1, 'lsups' },-- MODIFIER LETTER SMALL L
  ['l_uni0303.pc'] = { 0x029F, 0x0303, 'LtildePC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING TILDE
  ['l_uni0303.sc'] = { 0x029F, 0x0303, 'LtildeSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING TILDE
  ['lacute.pc'] = { 0x029F, 0x0301, 'LacutePC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING ACUTE ACCENT
  ['lacute.sc'] = { 0x029F, 0x0301, 'LacuteSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING ACUTE ACCENT
  ['lcaron.pc'] = { 0x029F, 0x0315, 'LcaronPC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA ABOVE RIGHT
  ['lcaron.sc'] = { 0x029F, 0x0315, 'LcaronSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA ABOVE RIGHT
  ['lcommaaccent.pc'] = { 0x029F, 0x0326, 'LcommaaccentPC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA BELOW
  ['lcommaaccent.sc'] = { 0x029F, 0x0326, 'LcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING COMMA BELOW
  ['ldot.pc'] = { 0x029F, 0x0358, 'LdotPC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT ABOVE RIGHT
  ['ldot.sc'] = { 0x029F, 0x0358, 'LdotSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT ABOVE RIGHT
  ['ldotbelow.pc'] = { 0x029F, 0x0323, 'LdotbelowPC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW
  ['ldotbelow.sc'] = { 0x029F, 0x0323, 'LdotbelowSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW
  ['ldotbelowmacron.pc'] = { 0x029F, 0x0323, 0x0304, 'LdotbelowmacronPC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW/COMBINING MACRON
  ['ldotbelowmacron.sc'] = { 0x029F, 0x0323, 0x0304, 'LdotbelowmacronSC' },-- LATIN LETTER SMALL CAPITAL L/COMBINING DOT BELOW/COMBINING MACRON
  ['leaf'] = { 0x1F342 },-- FALLEN LEAF
  ['lessequal.slant'] = { 0x2A7D, 'lessequalslant' },-- LESS-THAN OR SLANTED EQUAL TO
  ['lslash.pc'] = { 0x1D0C, 'LslashPC' },-- LATIN LETTER SMALL CAPITAL L WITH STROKE
  ['lslash.sc'] = { 0x1D0C, 'LslashSC' },-- LATIN LETTER SMALL CAPITAL L WITH STROKE
  ['m.pc'] = { 0x1D0D, 'mPC' },-- LATIN LETTER SMALL CAPITAL M
  ['m.sc'] = { 0x1D0D, 'mSC' },-- LATIN LETTER SMALL CAPITAL M
  ['m.superior.alt'] = { 0x1D50, 'msuperscript' },-- MODIFIER LETTER SMALL M
  ['m.sups'] = { 0x1D50, 'msups' },-- MODIFIER LETTER SMALL M
  ['married'] = { 0x26AD },-- MARRIAGE SYMBOL
  ['mdotbelow.pc'] = { 0x1D0D, 0x0323, 'MdotbelowPC' },-- LATIN LETTER SMALL CAPITAL M/COMBINING DOT BELOW
  ['mdotbelow.sc'] = { 0x1D0D, 0x0323, 'MdotbelowSC' },-- LATIN LETTER SMALL CAPITAL M/COMBINING DOT BELOW
  ['n.pc'] = { 0x0274, 'nPC' },-- LATIN LETTER SMALL CAPITAL N
  ['n.sc'] = { 0x0274, 'nSC' },-- LATIN LETTER SMALL CAPITAL N
  ['n.superior.alt'] = { 0x207F, 'nsuperscript' },-- SUPERSCRIPT LATIN SMALL LETTER N
  ['n.sups'] = { 0x207F, 'nsups' },-- SUPERSCRIPT LATIN SMALL LETTER N
  ['nacute.pc'] = { 0x0274, 0x0301, 'NacutePC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING ACUTE ACCENT
  ['nacute.sc'] = { 0x0274, 0x0301, 'NacuteSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING ACUTE ACCENT
  ['naira'] = { 0x20A6 },-- NAIRA SIGN
  ['ncaron.pc'] = { 0x0274, 0x030C, 'NcaronPC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING CARON
  ['ncaron.sc'] = { 0x0274, 0x030C, 'NcaronSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING CARON
  ['ncommaaccent.pc'] = { 0x0274, 0x0326, 'NcommaaccentPC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING COMMA BELOW
  ['ncommaaccent.sc'] = { 0x0274, 0x0326, 'NcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING COMMA BELOW
  ['ndotaccent.pc'] = { 0x0274, 0x0307, 'NdotaccentPC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT ABOVE
  ['ndotaccent.sc'] = { 0x0274, 0x0307, 'NdotaccentSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT ABOVE
  ['ndotbelow.pc'] = { 0x0274, 0x0323, 'NdotbelowPC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT BELOW
  ['ndotbelow.sc'] = { 0x0274, 0x0323, 'NdotbelowSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING DOT BELOW
  ['nine.inferior'] = { 0x2089, 'ninesubscript' },-- SUBSCRIPT NINE
  ['nine.inferior.alt'] = { 0x2089, 'ninesubscriptalt' },-- SUBSCRIPT NINE
  ['nine.superior.alt'] = { 0x2079, 'ninesuperscript' },-- SUPERSCRIPT NINE
  ['nine.sups'] = { 0x2079, 'ninesups' },-- SUPERSCRIPT NINE
  ['ntilde.pc'] = { 0x0274, 0x0303, 'NtildePC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING TILDE
  ['ntilde.sc'] = { 0x0274, 0x0303, 'NtildeSC' },-- LATIN LETTER SMALL CAPITAL N/COMBINING TILDE
  ['o.pc'] = { 0x1D0F, 'oPC' },-- LATIN LETTER SMALL CAPITAL O
  ['o.sc'] = { 0x1D0F, 'oSC' },-- LATIN LETTER SMALL CAPITAL O
  ['o.superior.alt'] = { 0x1D52, 'osuperscript' },-- MODIFIER LETTER SMALL O
  ['o.sups'] = { 0x1D52, 'osups' },-- MODIFIER LETTER SMALL O
  ['oacute.pc'] = { 0x1D0F, 0x0301, 'OacutePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING ACUTE ACCENT
  ['oacute.sc'] = { 0x1D0F, 0x0301, 'OacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING ACUTE ACCENT
  ['obreve.pc'] = { 0x1D0F, 0x0306, 'ObrevePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING BREVE
  ['obreve.sc'] = { 0x1D0F, 0x0306, 'ObreveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING BREVE
  ['ocaron.pc'] = { 0x1D0F, 0x030C, 'OcaronPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CARON
  ['ocaron.sc'] = { 0x1D0F, 0x030C, 'OcaronSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CARON
  ['ocircumflex.pc'] = { 0x1D0F, 0x0302, 'OcircumflexPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT
  ['ocircumflex.sc'] = { 0x1D0F, 0x0302, 'OcircumflexSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT
  ['ocircumflexacute.pc'] = { 0x1D0F, 0x0302, 0x0301, 'OcircumflexacutePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ocircumflexacute.sc'] = { 0x1D0F, 0x0302, 0x0301, 'OcircumflexacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING ACUTE ACCENT
  ['ocircumflexdotbelow.pc'] = { 0x1D0F, 0x0302, 0x0323, 'OcircumflexdotbelowPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ocircumflexdotbelow.sc'] = { 0x1D0F, 0x0302, 0x0323, 'OcircumflexdotbelowSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING DOT BELOW
  ['ocircumflexgrave.pc'] = { 0x1D0F, 0x0302, 0x0300, 'OcircumflexgravePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ocircumflexgrave.sc'] = { 0x1D0F, 0x0302, 0x0300, 'OcircumflexgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING GRAVE ACCENT
  ['ocircumflexhookabove.pc'] = { 0x1D0F, 0x0302, 0x0309, 'OcircumflexhookabovePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ocircumflexhookabove.sc'] = { 0x1D0F, 0x0302, 0x0309, 'OcircumflexhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING HOOK ABOVE
  ['ocircumflextilde.pc'] = { 0x1D0F, 0x0302, 0x0303, 'OcircumflextildePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['ocircumflextilde.sc'] = { 0x1D0F, 0x0302, 0x0303, 'OcircumflextildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING CIRCUMFLEX ACCENT/COMBINING TILDE
  ['odblgrave.pc'] = { 0x1D0F, 0x030F, 'OdblgravePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE GRAVE ACCENT
  ['odblgrave.sc'] = { 0x1D0F, 0x030F, 'OdblgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE GRAVE ACCENT
  ['odieresis.pc'] = { 0x1D0F, 0x0308, 'OdieresisPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DIAERESIS
  ['odieresis.sc'] = { 0x1D0F, 0x0308, 'OdieresisSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DIAERESIS
  ['odotbelow.pc'] = { 0x1D0F, 0x0323, 'OdotbelowPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOT BELOW
  ['odotbelow.sc'] = { 0x1D0F, 0x0323, 'OdotbelowSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOT BELOW
  ['oe.pc'] = { 0x0276, 'OEPC' },-- LATIN LETTER SMALL CAPITAL OE
  ['oe.sc'] = { 0x0276, 'OESC' },-- LATIN LETTER SMALL CAPITAL OE
  ['ograve.pc'] = { 0x1D0F, 0x0300, 'OgravePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING GRAVE ACCENT
  ['ograve.sc'] = { 0x1D0F, 0x0300, 'OgraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING GRAVE ACCENT
  ['ohm'] = { 0x2126 },-- OHM SIGN
  ['ohookabove.pc'] = { 0x1D0F, 0x0309, 'OhookabovePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HOOK ABOVE
  ['ohookabove.sc'] = { 0x1D0F, 0x0309, 'OhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HOOK ABOVE
  ['ohorn.pc'] = { 0x1D0F, 0x031B, 'OhornPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN
  ['ohorn.sc'] = { 0x1D0F, 0x031B, 'OhornSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN
  ['ohornacute.pc'] = { 0x1D0F, 0x031B, 0x0301, 'OhornacutePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING ACUTE ACCENT
  ['ohornacute.sc'] = { 0x1D0F, 0x031B, 0x0301, 'OhornacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING ACUTE ACCENT
  ['ohorndotbelow.pc'] = { 0x1D0F, 0x031B, 0x0323,  'OhorndotbelowPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING DOT BELOW
  ['ohorndotbelow.sc'] = { 0x1D0F, 0x031B, 0x0323,  'OhorndotbelowSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING DOT BELOW
  ['ohorngrave.pc'] = { 0x1D0F, 0x031B, 0x0300, 'OhorngravePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING GRAVE ACCENT
  ['ohorngrave.sc'] = { 0x1D0F, 0x031B, 0x0300, 'OhorngraveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING GRAVE ACCENT
  ['ohornhookabove.pc'] = { 0x1D0F, 0x031B, 0x0309, 'OhornhookabovePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING HOOK ABOVE
  ['ohornhookabove.sc'] = { 0x1D0F, 0x031B, 0x0309, 'OhornhookaboveSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING HOOK ABOVE
  ['ohorntilde.pc'] = { 0x1D0F, 0x031B, 0x0303, 'OhorntildePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING TILDE
  ['ohorntilde.sc'] = { 0x1D0F, 0x031B, 0x0303, 'OhorntildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING HORN/COMBINING TILDE
  ['ohungarumlaut.pc'] = { 0x1D0F, 0x030B, 'OhungarumlautPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE ACUTE ACCENT
  ['ohungarumlaut.sc'] = { 0x1D0F, 0x030B, 'OhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING DOUBLE ACUTE ACCENT
  ['omacron.pc'] = { 0x1D0F, 0x0304, 'OmacronPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING MACRON
  ['omacron.sc'] = { 0x1D0F, 0x0304, 'OmacronSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING MACRON
  ['one.inferior'] = { 0x2081, 'onesubscript' },-- SUBSCRIPT ONE
  ['one.inferior.alt'] = { 0x2081, 'onesubscriptalt' },-- SUBSCRIPT ONE
  ['one.superior.alt'] = { 0x00B9, 'onesuperscript' },-- SUPERSCRIPT ONE
  ['one.sups'] = { 0x00B9, 'onesups' },-- SUPERSCRIPT ONE
  ['oogonek.pc'] = { 0x1D0F, 0x0328, 'OogonekPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK
  ['oogonek.sc'] = { 0x1D0F, 0x0328, 'OogonekSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK
  ['oogonekacute'] = { 0x01EB, 0x0301 },-- LATIN SMALL LETTER O WITH OGONEK/COMBINING ACUTE ACCENT
  ['oogonekacute.pc'] = { 0x1D0F, 0x0328, 0x0301, 'OogonekacutePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['oogonekacute.sc'] = { 0x1D0F, 0x0328, 0x0301, 'OogonekacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING OGONEK/COMBINING ACUTE ACCENT
  ['orogate'] = { 0xA7C1 },-- LATIN SMALL LETTER OLD POLISH O
  ['oslash.pc'] = { 0x1D0F, 0x0338, 'OslashPC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING LONG SOLIDUS OVERLAY
  ['oslash.sc'] = { 0x1D0F, 0x0338, 'OslashSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING LONG SOLIDUS OVERLAY
  ['oslashacute.pc'] = { 0x1D0F, 0x0338, 0x0301, 'OslashacutePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING LONG SOLIDUS OVERLAY/COMBINING ACUTE ACCENT
  ['oslashacute.sc'] = { 0x1D0F, 0x0338, 0x0301, 'OslashacuteSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING LONG SOLIDUS OVERLAY/COMBINING ACUTE ACCENT
  ['otilde.pc'] = { 0x1D0F, 0x0303, 'OtildePC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING TILDE
  ['otilde.sc'] = { 0x1D0F, 0x0303, 'OtildeSC' },-- LATIN LETTER SMALL CAPITAL O/COMBINING TILDE
  ['p.pc'] = { 0x1D18, 'pPC' },-- LATIN LETTER SMALL CAPITAL P
  ['p.sc'] = { 0x1D18, 'pSC' },-- LATIN LETTER SMALL CAPITAL P
  ['p.superior.alt'] = { 0x1D56, 'psuperscript' },-- MODIFIER LETTER SMALL P
  ['p.sups'] = { 0x1D56, 'psups' },-- MODIFIER LETTER SMALL P
  ['parenleft.sups'] = { 0x207D, 'parenleftsups' },-- SUPERSCRIPT LEFT PARENTHESIS
  ['parenright.sups'] = { 0x207E, 'parenrightsups' },-- SUPERSCRIPT RIGHT PARENTHESIS
  ['permyriad'] = { 0x2031 },-- PER TEN THOUSAND SIGN
  ['perthousandzero'] = { 0x2080 },-- SUBSCRIPT ZERO
  ['peso'] = { 0xA750 },-- LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
  ['plus.sups'] = { 0x207A, 'plussups' },-- SUPERSCRIPT PLUS SIGN
  ['published'] = { 0x2117 },-- SOUND RECORDING COPYRIGHT
  ['q.pc'] = { 0xA7AF, 'qPC' },-- LATIN LETTER SMALL CAPITAL Q
  ['q.sc'] = { 0xA7AF, 'qSC' },-- LATIN LETTER SMALL CAPITAL Q
  ['q.superior.alt'] = { 0x107A5, 'qsuperscript' },-- MODIFIER LETTER SMALL Q
  ['q.sups'] = { 0x107A5, 'qsups' },-- MODIFIER LETTER SMALL Q
  ['quillbracketleft'] = { 0x2045 },-- LEFT SQUARE BRACKET WITH QUILL
  ['quillbracketright'] = { 0x2046 },-- RIGHT SQUARE BRACKET WITH QUILL
  ['r.pc'] = { 0x0280, 'rPC' },-- LATIN LETTER SMALL CAPITAL R
  ['r.sc'] = { 0x0280, 'rSC' },-- LATIN LETTER SMALL CAPITAL R
  ['r.superior.alt'] = { 0x02B3, 'rsuperscript' },-- MODIFIER LETTER SMALL R
  ['r.sups'] = { 0x02B3, 'rsups' },-- MODIFIER LETTER SMALL R
  ['racute.pc'] = { 0x0280, 0x0301, 'RacutePC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING ACUTE ACCENT
  ['racute.sc'] = { 0x0280, 0x0301, 'RacuteSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING ACUTE ACCENT
  ['rcaron.pc'] = { 0x0280, 0x030C, 'RcaronPC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING CARON
  ['rcaron.sc'] = { 0x0280, 0x030C, 'RcaronSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING CARON
  ['rcommaaccent.pc'] = { 0x0280, 0x0326, 'RcommaaccentPC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING COMMA BELOW
  ['rcommaaccent.sc'] = { 0x0280, 0x0326, 'RcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING COMMA BELOW
  ['rdblgrave.pc'] = { 0x0280, 0x030F, 'RdblgravePC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOUBLE GRAVE ACCENT
  ['rdblgrave.sc'] = { 0x0280, 0x030F, 'RdblgraveSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOUBLE GRAVE ACCENT
  ['rdotaccent.pc'] = { 0x0280, 0x0307, 'RdotaccentPC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT ABOVE
  ['rdotaccent.sc'] = { 0x0280, 0x0307, 'RdotaccentSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT ABOVE
  ['rdotbelow.pc'] = { 0x0280, 0x0323, 'RdotbelowPC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW
  ['rdotbelow.sc'] = { 0x0280, 0x0323, 'RdotbelowSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW
  ['rdotbelowmacron.pc'] = { 0x0280, 0x0323, 0x0304, 'RdotbelowmacronPC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW/COMBINING MACRON
  ['rdotbelowmacron.sc'] = { 0x0280, 0x0323, 0x0304, 'RdotbelowmacronSC' },-- LATIN LETTER SMALL CAPITAL R/COMBINING DOT BELOW/COMBINING MACRON
  ['recipe'] = { 0xA776 },-- LATIN LETTER SMALL CAPITAL RUM
  ['s.pc'] = { 0xA731, 'sPC' },-- LATIN LETTER SMALL CAPITAL S
  ['s.sc'] = { 0xA731, 'sSC' },-- LATIN LETTER SMALL CAPITAL S
  ['s.superior.alt'] = { 0x02E2, 'ssuperscript' },-- MODIFIER LETTER SMALL S
  ['s.sups'] = { 0x02E2, 'ssups' },-- MODIFIER LETTER SMALL S
  ['s_uni0219.sc'] = { 0xA731, 0x0326, 'ScommaaccentSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING COMMA BELOW
  ['sacute.pc'] = { 0xA731, 0x0301, 'SacutePC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING ACUTE ACCENT
  ['sacute.sc'] = { 0xA731, 0x0301, 'SacuteSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING ACUTE ACCENT
  ['scaron.pc'] = { 0xA731, 0x030C, 'ScaronPC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CARON
  ['scaron.sc'] = { 0xA731, 0x030C, 'ScaronSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CARON
  ['scedilla.pc'] = { 0xA731, 0x0327, 'ScedillaPC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CEDILLA
  ['scedilla.sc'] = { 0xA731, 0x0327, 'ScedillaSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CEDILLA
  ['scircumflex.pc'] = { 0xA731, 0x0302, 'ScircumflexPC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CIRCUMFLEX ACCENT
  ['scircumflex.sc'] = { 0xA731, 0x0302, 'ScircumflexSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING CIRCUMFLEX ACCENT
  ['sdotbelow.pc'] = { 0xA731, 0x0323, 'SdotbelowPC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING DOT BELOW
  ['sdotbelow.sc'] = { 0xA731, 0x0323, 'SdotbelowSC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING DOT BELOW
  ['servicemark'] = { 0x2120 },-- SERVICE MARK
  ['seven.inferior'] = { 0x2087, 'sevensubscript' },-- SUBSCRIPT SEVEN
  ['seven.inferior.alt'] = { 0x2087, 'sevensubscriptalt' },-- SUBSCRIPT SEVEN
  ['seven.superior.alt'] = { 0x2077, 'sevensuperscript' },-- SUPERSCRIPT SEVEN
  ['seven.sups'] = { 0x2077, 'sevensups' },-- SUPERSCRIPT SEVEN
  ['six.inferior'] = { 0x2086, 'sixsubscript' },-- SUBSCRIPT SIX
  ['six.inferior.alt'] = { 0x2086, 'sixsubscriptalt' },-- SUBSCRIPT SIX
  ['six.superior.alt'] = { 0x2076, 'sixsuperscript' },-- SUPERSCRIPT SIX
  ['six.sups'] = { 0x2076, 'sixsups' },-- SUPERSCRIPT SIX
  ['t.pc'] = { 0x1D1B, 'tPC' },-- LATIN LETTER SMALL CAPITAL T
  ['t.sc'] = { 0x1D1B, 'tSC' },-- LATIN LETTER SMALL CAPITAL T
  ['t.superior.alt'] = { 0x1D57, 'tsuperscript' },-- MODIFIER LETTER SMALL T
  ['t.sups'] = { 0x1D57, 'tsups' },-- MODIFIER LETTER SMALL T
  ['t_uni021B.sc'] = { 0x1D1B, 0x0326, 'TcommaaccentSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING COMMA BELOW
  ['t_uni0303.pc'] = { 0x1D1B, 0x0303, 'TtildePC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING TILDE
  ['t_uni0303.sc'] = { 0x1D1B, 0x0303, 'TtildeSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING TILDE
  ['tcaron.pc'] = { 0x1D1B, 0x030C, 'TcaronPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CARON
  ['tcaron.sc'] = { 0x1D1B, 0x030C, 'TcaronSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CARON
  ['tcedilla.pc'] = { 0x1D1B, 0x0327, 'TcedillaPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CEDILLA
  ['tcedilla.sc'] = { 0x1D1B, 0x0327, 'TcedillaSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING CEDILLA
  ['tdieresis.pc'] = { 0x1D1B, 0x0308, 'TdieresisPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DIAERESIS
  ['tdieresis.sc'] = { 0x1D1B, 0x0308, 'TdieresisSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DIAERESIS
  ['tdotbelow.pc'] = { 0x1D1B, 0x0323, 'TdotbelowPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DOT BELOW
  ['tdotbelow.sc'] = { 0x1D1B, 0x0323, 'TdotbelowSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING DOT BELOW
  ['three.inferior'] = { 0x2083, 'threesubscript' },-- SUBSCRIPT THREE
  ['three.inferior.alt'] = { 0x2083, 'threesubscriptalt' },-- SUBSCRIPT THREE
  ['three.superior.alt'] = { 0x00B3, 'threesuperscript' },-- SUPERSCRIPT THREE
  ['three.sups'] = { 0x00B3, 'threesups' },-- SUPERSCRIPT THREE
  ['threequartersemdash'] = { 0x2014 },-- EM DASH
  ['tieaccentcapital'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentcapital.new'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentlowercase'] = { 0x2040 },-- CHARACTER TIE
  ['tieaccentlowercase.new'] = { 0x2040 },-- CHARACTER TIE
  ['tlinebelow.pc'] = { 0x1D1B, 0x0331, 'TlinebelowPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING MACRON BELOW
  ['tlinebelow.sc'] = { 0x1D1B, 0x0331, 'TlinebelowSC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING MACRON BELOW
  ['two.inferior'] = { 0x2082, 'twosubscript' },-- SUBSCRIPT TWO
  ['two.inferior.alt'] = { 0x2082, 'twosubscriptalt' },-- SUBSCRIPT TWO
  ['two.superior.alt'] = { 0x00B2, 'twosuperscript' },-- SUPERSCRIPT TWO
  ['two.sups'] = { 0x00B2, 'twosups' },-- SUPERSCRIPT TWO
  ['u.pc'] = { 0x1D1C, 'uPC' },-- LATIN LETTER SMALL CAPITAL U
  ['u.sc'] = { 0x1D1C, 'uSC' },-- LATIN LETTER SMALL CAPITAL U
  ['u.superior.alt'] = { 0x1D58, 'usuperscript' },-- MODIFIER LETTER SMALL U
  ['u.sups'] = { 0x1D58, 'usups' },-- MODIFIER LETTER SMALL U
  ['uacute.pc'] = { 0x1D1C, 0x0301, 'UacutePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING ACUTE ACCENT
  ['uacute.sc'] = { 0x1D1C, 0x0301, 'UacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING ACUTE ACCENT
  ['ubreve.pc'] = { 0x1D1C, 0x0306, 'UbrevePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING BREVE
  ['ubreve.sc'] = { 0x1D1C, 0x0306, 'UbreveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING BREVE
  ['ubrevebelowinverted.pc'] = { 0x1D1C, 0x032F, 'UbrevebelowinvertedPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING INVERTED BREVE BELOW
  ['ubrevebelowinverted.sc'] = { 0x1D1C, 0x032F, 'UbrevebelowinvertedSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING INVERTED BREVE BELOW
  ['ucaron.pc'] = { 0x1D1C, 0x030C, 'UcaronPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CARON
  ['ucaron.sc'] = { 0x1D1C, 0x030C, 'UcaronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CARON
  ['ucircumflex.pc'] = { 0x1D1C, 0x0302, 'UcircumflexPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CIRCUMFLEX ACCENT
  ['ucircumflex.sc'] = { 0x1D1C, 0x0302, 'UcircumflexSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING CIRCUMFLEX ACCENT
  ['udblgrave.pc'] = { 0x1D1C, 0x030F, 'UdblgravePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE GRAVE ACCENT
  ['udblgrave.sc'] = { 0x1D1C, 0x030F, 'UdblgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE GRAVE ACCENT
  ['udieresis.pc'] = { 0x1D1C, 0x0308, 'UdieresisPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS
  ['udieresis.sc'] = { 0x1D1C, 0x0308, 'UdieresisSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS
  ['udieresisacute.pc'] = { 0x1D1C, 0x0308, 0x0301, 'UdieresisacutePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['udieresisacute.sc'] = { 0x1D1C, 0x0308, 0x0301, 'UdieresisacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING ACUTE ACCENT
  ['udieresiscaron.pc'] = { 0x1D1C, 0x0308, 0x030C, 'UdieresiscaronPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING CARON
  ['udieresiscaron.sc'] = { 0x1D1C, 0x0308, 0x030C, 'UdieresiscaronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING CARON
  ['udieresisgrave.pc'] = { 0x1D1C, 0x0308, 0x0300, 'UdieresisgravePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING GRAVE ACCENT
  ['udieresisgrave.sc'] = { 0x1D1C, 0x0308, 0x0300, 'UdieresisgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DIAERESIS/COMBINING GRAVE ACCENT
  ['udotbelow.pc'] = { 0x1D1C, 0x0323, 'UdotbelowPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOT BELOW
  ['udotbelow.sc'] = { 0x1D1C, 0x0323, 'UdotbelowSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOT BELOW
  ['ugrave.pc'] = { 0x1D1C, 0x0300, 'UgravePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING GRAVE ACCENT
  ['ugrave.sc'] = { 0x1D1C, 0x0300, 'UgraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING GRAVE ACCENT
  ['uhookabove.pc'] = { 0x1D1C, 0x0309, 'UhookabovePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HOOK ABOVE
  ['uhookabove.sc'] = { 0x1D1C, 0x0309, 'UhookaboveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HOOK ABOVE
  ['uhorn.pc'] = { 0x1D1C, 0x031B, 'UhornPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN
  ['uhorn.sc'] = { 0x1D1C, 0x031B, 'UhornSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN
  ['uhornacute.pc'] = { 0x1D1C, 0x031B, 0x0301, 'UhornacutePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING ACUTE ACCENT
  ['uhornacute.sc'] = { 0x1D1C, 0x031B, 0x0301, 'UhornacuteSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING ACUTE ACCENT
  ['uhorndotbelow.pc'] = { 0x1D1C, 0x031B, 0x0323,  'UhorndotbelowPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING DOT BELOW
  ['uhorndotbelow.sc'] = { 0x1D1C, 0x031B, 0x0323,  'UhorndotbelowSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING DOT BELOW
  ['uhorngrave.pc'] = { 0x1D1C, 0x031B, 0x0300, 'UhorngravePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING GRAVE ACCENT
  ['uhorngrave.sc'] = { 0x1D1C, 0x031B, 0x0300, 'UhorngraveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING GRAVE ACCENT
  ['uhornhookabove.pc'] = { 0x1D1C, 0x031B, 0x0309, 'UhornhookabovePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING HOOK ABOVE
  ['uhornhookabove.sc'] = { 0x1D1C, 0x031B, 0x0309, 'UhornhookaboveSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING HOOK ABOVE
  ['uhorntilde.pc'] = { 0x1D1C, 0x031B, 0x0303, 'UhorntildePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING TILDE
  ['uhorntilde.sc'] = { 0x1D1C, 0x031B, 0x0303, 'UhorntildeSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING HORN/COMBINING TILDE
  ['uhungarumlaut.pc'] = { 0x1D1C, 0x030B, 'UhungarumlautPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE ACUTE ACCENT
  ['uhungarumlaut.sc'] = { 0x1D1C, 0x030B, 'UhungarumlautSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING DOUBLE ACUTE ACCENT
  ['umacron.pc'] = { 0x1D1C, 0x0304, 'UmacronPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING MACRON
  ['umacron.sc'] = { 0x1D1C, 0x0304, 'UmacronSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING MACRON
  ['uni0219.pc'] = { 0xA731, 0x0326, 'ScommaaccentPC' },-- LATIN LETTER SMALL CAPITAL S/COMBINING COMMA BELOW
  ['uni021B.pc'] = { 0x1D1B, 0x0326, 'TcommaaccentPC' },-- LATIN LETTER SMALL CAPITAL T/COMBINING COMMA BELOW
  ['uni2017'] = { 0x2217, 'asteriskcentered' },-- ASTERISK OPERATOR
  ['uogonek.pc'] = { 0x1D1C, 0x0328, 'UogonekPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING OGONEK
  ['uogonek.sc'] = { 0x1D1C, 0x0328, 'UogonekSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING OGONEK
  ['uring.pc'] = { 0x1D1C, 0x030A, 'UringPC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING RING ABOVE
  ['uring.sc'] = { 0x1D1C, 0x030A, 'UringSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING RING ABOVE
  ['utilde.pc'] = { 0x1D1C, 0x0303, 'UtildePC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING TILDE
  ['utilde.sc'] = { 0x1D1C, 0x0303, 'UtildeSC' },-- LATIN LETTER SMALL CAPITAL U/COMBINING TILDE
  ['v.pc'] = { 0x1D20, 'vPC' },-- LATIN LETTER SMALL CAPITAL V
  ['v.sc'] = { 0x1D20, 'vSC' },-- LATIN LETTER SMALL CAPITAL V
  ['v.superior.alt'] = { 0x1D5B, 'vsuperscript' },-- MODIFIER LETTER SMALL V
  ['v.sups'] = { 0x1D5B, 'vsups' },-- MODIFIER LETTER SMALL V
  ['w.pc'] = { 0x1D21, 'wPC' },-- LATIN LETTER SMALL CAPITAL W
  ['w.sc'] = { 0x1D21, 'wSC' },-- LATIN LETTER SMALL CAPITAL W
  ['w.superior.alt'] = { 0x02B7, 'wsuperscript' },-- MODIFIER LETTER SMALL W
  ['w.sups'] = { 0x02B7, 'wsups' },-- MODIFIER LETTER SMALL W
  ['wacute.pc'] = { 0x1D21, 0x0301, 'WacutePC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING ACUTE ACCENT
  ['wacute.sc'] = { 0x1D21, 0x0301, 'WacuteSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING ACUTE ACCENT
  ['wcircumflex.pc'] = { 0x1D21, 0x0302, 'WcircumflexPC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING CIRCUMFLEX ACCENT
  ['wcircumflex.sc'] = { 0x1D21, 0x0302, 'WcircumflexSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING CIRCUMFLEX ACCENT
  ['wdieresis.pc'] = { 0x1D21, 0x0308, 'WdieresisPC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING DIAERESIS
  ['wdieresis.sc'] = { 0x1D21, 0x0308, 'WdieresisSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING DIAERESIS
  ['wgrave.pc'] = { 0x1D21, 0x0300, 'WgravePC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING GRAVE ACCENT
  ['wgrave.sc'] = { 0x1D21, 0x0300, 'WgraveSC' },-- LATIN LETTER SMALL CAPITAL W/COMBINING GRAVE ACCENT
  ['x.superior.alt'] = { 0x02E3, 'xsuperscript' },-- MODIFIER LETTER SMALL X
  ['x.sups'] = { 0x02E3, 'xsups' },-- MODIFIER LETTER SMALL X
  ['y.pc'] = { 0x028F, 'yPC' },-- LATIN LETTER SMALL CAPITAL Y
  ['y.sc'] = { 0x028F, 'ySC' },-- LATIN LETTER SMALL CAPITAL Y
  ['y.superior.alt'] = { 0x02B8, 'ysuperscript' },-- MODIFIER LETTER SMALL Y
  ['y.sups'] = { 0x02B8, 'ysups' },-- MODIFIER LETTER SMALL Y
  ['yacute.pc'] = { 0x028F, 0x0301, 'YacutePC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING ACUTE ACCENT
  ['yacute.sc'] = { 0x028F, 0x0301, 'YacuteSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING ACUTE ACCENT
  ['ycircumflex.pc'] = { 0x028F, 0x0302, 'YcircumflexPC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING CIRCUMFLEX ACCENT
  ['ycircumflex.sc'] = { 0x028F, 0x0302, 'YcircumflexSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING CIRCUMFLEX ACCENT
  ['ydieresis.pc'] = { 0x028F, 0x0308, 'YdieresisPC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DIAERESIS
  ['ydieresis.sc'] = { 0x028F, 0x0308, 'YdieresisSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DIAERESIS
  ['ydotbelow.pc'] = { 0x028F, 0x0323, 'YdotbelowPC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DOT BELOW
  ['ydotbelow.sc'] = { 0x028F, 0x0323, 'YdotbelowSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING DOT BELOW
  ['ygrave.pc'] = { 0x028F, 0x0300, 'YgravePC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING GRAVE ACCENT
  ['ygrave.sc'] = { 0x028F, 0x0300, 'YgraveSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING GRAVE ACCENT
  ['yhookabove.pc'] = { 0x028F, 0x0309, 'YhookabovePC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING HOOK ABOVE
  ['yhookabove.sc'] = { 0x028F, 0x0309, 'YhookaboveSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING HOOK ABOVE
  ['ytilde.pc'] = { 0x028F, 0x0303, 'YtildePC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING TILDE
  ['ytilde.sc'] = { 0x028F, 0x0303, 'YtildeSC' },-- LATIN LETTER SMALL CAPITAL Y/COMBINING TILDE
  ['z.pc'] = { 0x1D22, 'zPC' },-- LATIN LETTER SMALL CAPITAL Z
  ['z.sc'] = { 0x1D22, 'zSC' },-- LATIN LETTER SMALL CAPITAL Z
  ['z.superior.alt'] = { 0x1DBB, 'zsuperscript' },-- MODIFIER LETTER SMALL Z
  ['z.sups'] = { 0x1DBB, 'zsups' },-- MODIFIER LETTER SMALL Z
  ['zacute.pc'] = { 0x1D22, 0x0301, 'ZacutePC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING ACUTE ACCENT
  ['zacute.sc'] = { 0x1D22, 0x0301, 'ZacuteSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING ACUTE ACCENT
  ['zcaron.pc'] = { 0x1D22, 0x030C, 'ZcaronPC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING CARON
  ['zcaron.sc'] = { 0x1D22, 0x030C, 'ZcaronSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING CARON
  ['zdotaccent.pc'] = { 0x1D22, 0x0307, 'ZdotaccentPC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT ABOVE
  ['zdotaccent.sc'] = { 0x1D22, 0x0307, 'ZdotaccentSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT ABOVE
  ['zdotbelow.pc'] = { 0x1D22, 0x0323, 'ZdotbelowPC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT BELOW
  ['zdotbelow.sc'] = { 0x1D22, 0x0323, 'ZdotbelowSC' },-- LATIN LETTER SMALL CAPITAL Z/COMBINING DOT BELOW
  ['zero.inferior'] = { 0x2080, 'zerosubscript' },-- SUBSCRIPT ZERO
  ['zero.inferior.alt'] = { 0x2080, 'zerosubscriptalt' },-- SUBSCRIPT ZERO
  ['zero.superior.alt'] = { 0x2070, 'zerosuperscript' },-- SUPERSCRIPT ZERO
  ['zero.sups'] = { 0x2070, 'zerosups' },-- SUPERSCRIPT ZERO
}
