return {
  ['APLup'] = { 0x25B3 },-- WHITE UP-POINTING TRIANGLE
  ['lhd'] = { 0x25C1 },-- WHITE LEFT-POINTING TRIANGLE
  ['unlhd'] = { 0x22B4 },-- NORMAL SUBGROUP OF OR EQUAL TO
  ['rhd'] = { 0x25B7 },-- WHITE RIGHT-POINTING TRIANGLE
  ['unrhd'] = { 0x22B5 },-- CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
  ['recorder'] = { 0x2315 },-- TELEPHONE RECORDER
  ['phone'] = { 0x260E },-- BLACK TELEPHONE
  ['checked'] = { 0x2713 },-- CHECK MARK
  ['pointer'] = { 0x1F83A },-- RIGHTWARDS SQUARED ARROW
  ['bell'] = { 0x1F514 },-- BELL
  ['eigthnote'] = { 0x266A },-- EIGHTH NOTE
  ['halfnote'] = { 0x1D15E },-- MUSICAL SYMBOL HALF NOTE
  ['fullnote'] = { 0x1D15D },-- MUSICAL SYMBOL WHOLE NOTE
  ['twonotes'] = { 0x266B },-- BEAMED EIGHTH NOTES
  ['LHD'] = { 0x25C0 },-- BLACK LEFT-POINTING TRIANGLE
  ['RHD'] = { 0x25B6 },-- BLACK RIGHT-POINTING TRIANGLE
  ['lightning'] = { 0x21AF },-- DOWNWARDS ZIGZAG ARROW
  ['ascnode'] = { 0x260A },-- ASCENDING NODE
  ['descnode'] = { 0x260B },-- DESCENDING NODE
  ['invdiameter'] = { 0x2349 },-- APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH
  ['logof'] = { 0x1F7AF, 0x20DD },-- LIGHT FIVE SPOKED ASTERISK/COMBINING ENCLOSING CIRCLE
  ['aries'] = { 0x2648 },-- ARIES
  ['invneg'] = { 0x2310 },-- REVERSED NOT SIGN
  ['clock'] = { 0x1F552 },-- CLOCK FACE THREE OCLOCK
  ['varprop'] = { 0x221D },-- PROPORTIONAL TO
  ['varangle'] = { 0x2222 },-- SPHERICAL ANGLE
  ['diameter'] = { 0x2300 },-- DIAMETER SIGN
  ['CIRCLE'] = { 0x25CF },-- BLACK CIRCLE
  ['rightturn'] = { 0x21BB },-- CLOCKWISE OPEN CIRCLE ARROW
  ['leftturn'] = { 0x21BA },-- ANTICLOCKWISE OPEN CIRCLE ARROW
  ['Circle'] = { 0x25CB },-- WHITE CIRCLE
  ['leftmoon'] = { 0x263E },-- LAST QUARTER MOON
  ['rightmoon'] = { 0x263D },-- FIRST QUARTER MOON
  ['mercury'] = { 0x263F },-- MERCURY
  ['leftarrowhead'] = { 0x1F890 },-- LEFTWARDS TRIANGLE ARROWHEAD
  ['rightarrowhead'] = { 0x1F892 },-- RIGHTWARDS TRIANGLE ARROWHEAD
  ['uparrowhead'] = { 0x1F891 },-- UPWARDS TRIANGLE ARROWHEAD
  ['downarrowhead'] = { 0x1F893 },-- DOWNWARDS TRIANGLE ARROWHEAD
  ['smiley'] = { 0x263A },-- WHITE SMILING FACE
  ['blacksmiley'] = { 0x263B },-- BLACK SMILING FACE
  ['frownie'] = { 0x2639 },-- WHITE FROWNING FACE
  ['agemO'] = { 0x2127 },-- INVERTED OHM SIGN
  ['Bowtie'] = { 0x22C8 },-- BOWTIE
  ['Box'] = { 0x25A1 },-- WHITE SQUARE
  ['Diamond'] = { 0x25C7 },-- WHITE DIAMOND
  ['XBox'] = { 0x22A0 },-- SQUARED TIMES
  ['lozenge'] = { 0x2311 },-- SQUARE LOZENGE
  ['kreuz'] = { 0x2720 },-- MALTESE CROSS
  ['hexagon'] = { 0x2B21 },-- WHITE HEXAGON
  ['octagon'] = { 0x2BC3 },-- HORIZONTAL BLACK OCTAGON
  ['varhexagon'] = { 0x2B21 },-- WHITE HEXAGON
  ['AC'] = { 0x223C },-- TILDE OPERATOR
  ['leadsto'] = { 0x2933 },-- WAVE ARROW POINTING DIRECTLY RIGHT
  ['sqsubset'] = { 0x228F },-- SQUARE IMAGE OF
  ['sqsupset'] = { 0x2290 },-- SQUARE ORIGINAL OF
  ['apprle'] = { 0x2272 },-- LESS-THAN OR EQUIVALENT TO
  ['apprge'] = { 0x2273 },-- GREATER-THAN OR EQUIVALENT TO
  ['VHF'] = { 0x224B },-- TRIPLE TILDE
  ['hexstar'] = { 0x26B9 },-- SEXTILE
  ['varhexstar'] = { 0xFF0A },-- FULLWIDTH ASTERISK
  ['davidsstar'] = { 0x2721 },-- STAR OF DAVID
  ['pentagon'] = { 0x2B20 },-- WHITE PENTAGON
  ['pentastar'] = { 0x1F7AF },-- LIGHT FIVE SPOKED ASTERISK
  ['APLdown'] = { 0x25BD },-- WHITE DOWN-POINTING TRIANGLE
  ['LEFTCIRCLE'] = { 0x25D6 },-- LEFT HALF BLACK CIRCLE
  ['RIGHTCIRCLE'] = { 0x25D7 },-- RIGHT HALF BLACK CIRCLE
  ['Leftcircle'] = { 0x25D0 },-- CIRCLE WITH LEFT HALF BLACK
  ['Rightcircle'] = { 0x25D1 },-- CIRCLE WITH RIGHT HALF BLACK
  ['UParrow'] = { 0x25B2 },-- BLACK UP-POINTING TRIANGLE
  ['DOWNarrow'] = { 0x25BC },-- BLACK DOWN-POINTING TRIANGLE
  ['Paragraph'] = { 0x00A7 },-- SECTION SIGN
  ['zh'] = { 0x0292 },-- LATIN SMALL LETTER EZH
  ['gluonelement'] = { 0x0263 },-- LATIN SMALL LETTER GAMMA
  ['gluonbelement'] = { 0x25DC },-- UPPER LEFT QUADRANT CIRCULAR ARC
  ['gluoneelement'] = { 0x25DD },-- UPPER RIGHT QUADRANT CIRCULAR ARC
  ['applecmd'] = { 0x2318 },-- PLACE OF INTEREST SIGN
  ['inve'] = { 0x0259 },-- LATIN SMALL LETTER SCHWA
  ['conjunction'] = { 0x260C },-- CONJUNCTION
  ['opposition'] = { 0x260D },-- OPPOSITION
  ['jupiter'] = { 0x2643 },-- JUPITER
  ['saturn'] = { 0x2644 },-- SATURN
  ['uranus'] = { 0x26E2 },-- ASTRONOMICAL SYMBOL FOR URANUS
  ['neptun'] = { 0x2646 },-- NEPTUNE
  ['pluto'] = { 0x2647 },-- PLUTO
  ['taurus'] = { 0x2649 },-- TAURUS
  ['gemini'] = { 0x264A },-- GEMINI
  ['cancer'] = { 0x264B },-- CANCER
  ['virgo'] = { 0x264D },-- VIRGO
  ['libra'] = { 0x264E },-- LIBRA
  ['scorpio'] = { 0x264F },-- SCORPIUS
  ['sagittarius'] = { 0x2650 },-- SAGITTARIUS
  ['capricorn'] = { 0x2651 },-- CAPRICORN
  ['aquarius'] = { 0x2652 },-- AQUARIUS
  ['pisces'] = { 0x2653 },-- PISCES
  ['permil'] = { 0x2030 },-- PER MILLE SIGN
  ['dh'] = { 0x00F0 },-- LATIN SMALL LETTER ETH
  ['openo'] = { 0x0254 },-- LATIN SMALL LETTER OPEN O
  ['ataribox'] = { 0x1FBBF },-- NEGATIVE DIAGONAL DIAMOND
  ['APLuparrowbox'] = { 0x2350 },-- APL FUNCTIONAL SYMBOL QUAD UPWARDS ARROW
  ['APLdownarrowbox'] = { 0x2357 },-- APL FUNCTIONAL SYMBOL QUAD DOWNWARDS ARROW
  ['APLleftarrowbox'] = { 0x2347 },-- APL FUNCTIONAL SYMBOL QUAD LEFTWARDS ARROW
  ['APLrightarrowbox'] = { 0x2348 },-- APL FUNCTIONAL SYMBOL QUAD RIGHTWARDS ARROW
  ['varint'] = { 0x222B },-- INTEGRAL
  ['iint'] = { 0x222C },-- DOUBLE INTEGRAL
  ['iiint'] = { 0x222D },-- TRIPLE INTEGRAL
  ['varoint'] = { 0x222E },-- CONTOUR INTEGRAL
  ['oiint'] = { 0x222F },-- SURFACE INTEGRAL
  ['dispvarint'] = { 0x222B, 0xFE01 },-- INTEGRAL/VARIATION SELECTOR-2
  ['dispiint'] = { 0x222C, 0xFE01 },-- DOUBLE INTEGRAL/VARIATION SELECTOR-2
  ['dispiiint'] = { 0x222D, 0xFE01 },-- TRIPLE INTEGRAL/VARIATION SELECTOR-2
  ['dispvaroint'] = { 0x222E, 0xFE01 },-- CONTOUR INTEGRAL/VARIATION SELECTOR-2
  ['dispoiint'] = { 0x222F, 0xFE01 },-- SURFACE INTEGRAL/VARIATION SELECTOR-2
  ['brokenvert'] = { 0x00A6 },-- BROKEN BAR
  ['APLinput'] = { 0x235E },-- APL FUNCTIONAL SYMBOL QUOTE QUAD
  ['APLbox'] = { 0x2395 },-- APL FUNCTIONAL SYMBOL QUAD
  ['APLcomment'] = { 0x235D },-- APL FUNCTIONAL SYMBOL UP SHOE JOT
  }
