return {
  ['.null'] = { 0x0000 },-- <control>
  ['nonmarkingreturn'] = { 0x240D },-- SYMBOL FOR CARRIAGE RETURN
  ['MVspace'] = { 0x0020 },-- SPACE
  ['Stopsign'] = { 0x1F6D1 },-- OCTAGONAL SIGN
  ['Beam'] = { 0x2393 },-- DIRECT CURRENT SYMBOL FORM TWO
  ['Bearing'] = { 0x25B3, 0x030A },-- WHITE UP-POINTING TRIANGLE/COMBINING RING ABOVE
  ['LooseBearing'] = { 0x29CB, 0x030A },-- TRIANGLE WITH UNDERBAR/COMBINING RING ABOVE
  ['FixedBearing'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['LeftTorque'] = { 0x2939 },-- LEFT-SIDE ARC ANTICLOCKWISE ARROW
  ['RightTorque'] = { 0x2938 },-- RIGHT-SIDE ARC CLOCKWISE ARROW
  ['MVLeftBracket'] = { 0x0028 },-- LEFT PARENTHESIS
  ['MVRightBracket'] = { 0x0029 },-- RIGHT PARENTHESIS
  ['MVMultiplication'] = { 0x00D7 },-- MULTIPLICATION SIGN
  ['MVPlus'] = { 0x002B },-- PLUS SIGN
  ['MVComma'] = { 0x002C },-- COMMA
  ['MVMinus'] = { 0x2212 },-- MINUS SIGN
  ['MVPeriod'] = { 0x002E },-- FULL STOP
  ['MVDivision'] = { 0x2215 },-- DIVISION SLASH
  ['MVZero'] = { 0x0030 },-- DIGIT ZERO
  ['MVOne'] = { 0x0031 },-- DIGIT ONE
  ['MVTwo'] = { 0x0032 },-- DIGIT TWO
  ['MVThree'] = { 0x0033 },-- DIGIT THREE
  ['MVFour'] = { 0x0034 },-- DIGIT FOUR
  ['MVFive'] = { 0x0035 },-- DIGIT FIVE
  ['MVSix'] = { 0x0036 },-- DIGIT SIX
  ['MVSeven'] = { 0x0037 },-- DIGIT SEVEN
  ['MVEight'] = { 0x0038 },-- DIGIT EIGHT
  ['MVNine'] = { 0x0039 },-- DIGIT NINE
  ['MVRightArrow'] = { 0x2192 },-- RIGHTWARDS ARROW
  ['Conclusion'] = { 0x21D2 },-- RIGHTWARDS DOUBLE ARROW
  ['LessOrEqual'] = { 0x29A4 },-- ANGLE WITH UNDERBAR
  ['Corresponds'] = { 0x2258 },-- CORRESPONDS TO
  ['LargerOrEqual'] = { 0x29A5 },-- REVERSED ANGLE WITH UNDERBAR
  ['Equivalence'] = { 0x21D4 },-- LEFT RIGHT DOUBLE ARROW
  ['MVAt'] = { 0x0040 },-- COMMERCIAL AT
  ['Pickup'] = { 0x00F8 },-- LATIN SMALL LETTER O WITH STROKE
  ['Letter'] = { 0x2709 },-- ENVELOPE
  ['CESign'] = { 0x20A0 },-- EURO-CURRENCY SIGN
  ['EurDig'] = { 0x20AC },-- EURO SIGN
  ['Lightning'] = { 0x21AF },-- DOWNWARDS ZIGZAG ARROW
  ['BOLogo'] = { 0x0042, 0x004F },-- LATIN CAPITAL LETTER B/LATIN CAPITAL LETTER O
  ['BarOver'] = { 0x0305 },-- COMBINING OVERLINE
  ['Mobilefone'] = { 0x1F4F1 },-- MOBILE PHONE
  ['Industry'] = { 0x1F3ED },-- FACTORY
  ['Estatically'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Coffeecup'] = { 0x2615 },-- HOT BEVERAGE
  ['Lineload'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['BOLogoL'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['BOLogoP'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['HollowBox'] = { 0x25A1 },-- WHITE SQUARE
  ['ArrowOver'] = { 0x20D7 },-- COMBINING RIGHT ARROW ABOVE
  ['LeftScissors'] = { 0x2702 },-- BLACK SCISSORS
  ['CuttingLine'] = { 0x2504 },-- BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  ['RightScissors'] = { 0x2702 },-- BLACK SCISSORS
  ['Telefon'] = { 0x260E },-- BLACK TELEPHONE
  ['ClockLogo'] = { 0x1F552 },-- CLOCK FACE THREE OCLOCK
  ['CheckedBox'] = { 0x1F5F9 },-- BALLOT BOX WITH BOLD CHECK
  ['AngleSign'] = { 0x2222 },-- SPHERICAL ANGLE
  ['CrossedBox'] = { 0x1F5F7 },-- BALLOT BOX WITH BOLD SCRIPT X
  ['YinYang'] = { 0x262F },-- YIN YANG
  ['PointingHand'] = { 0x261E },-- WHITE RIGHT POINTING INDEX
  ['Divides'] = { 0x2223 },-- DIVIDES
  ['DividesNot'] = { 0x2224 },-- DOES NOT DIVIDE
  ['Congruent'] = { 0x2261 },-- IDENTICAL TO
  ['NotCongruent'] = { 0x2262 },-- NOT IDENTICAL TO
  ['StrikingThrough'] = { 0x0338 },-- COMBINING LONG SOLIDUS OVERLAY
  ['Explosionsafe'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Laserbeam'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['WritingHand'] = { 0x270D },-- WRITING HAND
  ['EurHv'] = { 0x20AC },-- EURO SIGN
  ['EurCr'] = { 0x20AC },-- EURO SIGN
  ['EurTm'] = { 0x20AC },-- EURO SIGN
  ['PeaceDove'] = { 0x1F54A },-- DOVE OF PEACE
  ['barOver'] = { 0x203E },-- OVERLINE
  ['Biohazard'] = { 0x2623 },-- BIOHAZARD SIGN
  ['Info'] = { 0x2139 },-- INFORMATION SOURCE
  ['Radioactivity'] = { 0x2622 },-- RADIOACTIVE SIGN
  ['EMail'] = { 0x1F4E7 },-- E-MAIL SYMBOL
  ['MVArrowDown'] = { 0x2193 },-- DOWNWARDS ARROW
  ['Mundus'] = { 0x1F30D },-- EARTH GLOBE EUROPE-AFRICA
  ['BSEFree'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Football'] = { 0x26BD },-- SOCCER BALL
  ['arrowOver'] = { 0x20D7 },-- COMBINING RIGHT ARROW ABOVE
  ['CutLeft'] = { 0x2701 },-- UPPER BLADE SCISSORS
  ['CutLine'] = { 0x2504 },-- BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  ['CutRight'] = { 0x2701 },-- UPPER BLADE SCISSORS
  ['fax'] = { 0x1F5B7 },-- FAX ICON
  ['FAX'] = { 0x1F5B7 },-- FAX ICON
  ['Fax'] = { 0x1F5B7 },-- FAX ICON
  ['Wheelchair'] = { 0x267F },-- WHEELCHAIR SYMBOL
  ['Gentsroom'] = { 0x1F6B9 },-- MENS SYMBOL
  ['Ladiesroom'] = { 0x1F6BA },-- WOMENS SYMBOL
  ['EmailCT'] = { 0x2301 },-- ELECTRIC ARROW
  ['Neutral'] = { 0x26B2 },-- NEUTER
  ['Male'] = { 0x2642 },-- MALE SIGN
  ['Hermaphrodite'] = { 0x26A5 },-- MALE AND FEMALE SIGN
  ['Female'] = { 0x2640 },-- FEMALE SIGN
  ['HERMAPHRODITE'] = { 0x26A5 },-- MALE AND FEMALE SIGN
  ['FEMALE'] = { 0x2640 },-- FEMALE SIGN
  ['MALE'] = { 0x2642 },-- MALE SIGN
  ['MaleMale'] = { 0x26A3 },-- DOUBLED MALE SIGN
  ['FemaleFemale'] = { 0x26A2 },-- DOUBLED FEMALE SIGN
  ['FemaleMale'] = { 0x26A4 },-- INTERLOCKED FEMALE AND MALE SIGN
  ['Cross'] = { 0x271D },-- LATIN CROSS
  ['CeltCross'] = { 0x1F548 },-- CELTIC CROSS
  ['Ankh'] = { 0x2625 },-- ANKH
  ['WashCotton'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['WashSynthetics'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['WashWool'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Heart'] = { 0x2661 },-- WHITE HEART SUIT
  ['EstimatedSign'] = { 0x212E },-- ESTIMATED SYMBOL
  ['Tumbler'] = { 0x233C },-- APL FUNCTIONAL SYMBOL QUAD CIRCLE
  ['NoTumbler'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['OktoSteel'] = { 0x2BC3 },-- HORIZONTAL BLACK OCTAGON
  ['HexaSteel'] = { 0x2B23 },-- HORIZONTAL BLACK HEXAGON
  ['SquareSteel'] = { 0x25A0 },-- BLACK SQUARE
  ['RectSteel'] = { 0x25AE },-- BLACK VERTICAL RECTANGLE
  ['CircSteel'] = { 0x25CF },-- BLACK CIRCLE
  ['FlatSteel'] = { 0x25AC },-- BLACK RECTANGLE
  ['SquarePipe'] = { 0x1F791 },-- HEAVY WHITE SQUARE
  ['RectPipe'] = { 0x25AF },-- WHITE VERTICAL RECTANGLE
  ['LSteel'] = { 0x221F },-- RIGHT ANGLE
  ['TTSteel'] = { 0x2336 },-- APL FUNCTIONAL SYMBOL I-BEAM
  ['CircPipe'] = { 0x1F787 },-- HEAVY WHITE CIRCLE
  ['TSteel'] = { 0x2533 },-- BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
  ['RoundedLSteel'] = { 0x221F },-- RIGHT ANGLE
  ['RoundedTTSteel'] = { 0x2336 },-- APL FUNCTIONAL SYMBOL I-BEAM
  ['RoundedTSteel'] = { 0x2533 },-- BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
  ['NoBreakSpace'] = { 0x00A0 },-- NO-BREAK SPACE
  ['Shilling'] = { 0x00DF },-- LATIN SMALL LETTER SHARP S
  ['Deleatur'] = { 0x2421 },-- SYMBOL FOR DELETE
  ['Pfund'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['EUR'] = { 0x20AC },-- EURO SIGN
  ['Bouquet'] = { 0x1F490 },-- BOUQUET
  ['EyesDollar'] = { 0x0024 },-- DOLLAR SIGN
  ['Frowny'] = { 0x2639 },-- WHITE FROWNING FACE
  ['NoChemicalCleaning'] = { 0x2297 },-- CIRCLED TIMES
  ['Smiley'] = { 0x263A },-- WHITE SMILING FACE
  ['CircledA'] = { 0x24B6 },-- CIRCLED LATIN CAPITAL LETTER A
  ['CleaningA'] = { 0x24B6 },-- CIRCLED LATIN CAPITAL LETTER A
  ['CleaningP'] = { 0x24C5 },-- CIRCLED LATIN CAPITAL LETTER P
  ['SoftHyphen'] = { 0x00AD },-- SOFT HYPHEN
  ['Bicycle'] = { 0x1F6B2 },-- BICYCLE
  ['ironing'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Ironing'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['IRONING'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['NoIroning'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['MineSign'] = { 0x2692 },-- HAMMER AND PICK
  ['RewindToIndex'] = { 0x23EE },-- BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR
  ['RewindToStart'] = { 0x007C, 0x1F780 },-- VERTICAL LINE/BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE
  ['Rewind'] = { 0x1F780 },-- BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE
  ['Forward'] = { 0x1F782 },-- BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE
  ['ForwardToEnd'] = { 0x1F782, 0x007C },-- BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE/VERTICAL LINE
  ['ForwardToIndex'] = { 0x23ED },-- BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR
  ['MoveUp'] = { 0x25B2 },-- BLACK UP-POINTING TRIANGLE
  ['MoveDown'] = { 0x25BC },-- BLACK DOWN-POINTING TRIANGLE
  ['ToTop'] = { 0x25B2, 0x0305 },-- BLACK UP-POINTING TRIANGLE/COMBINING OVERLINE
  ['ToBottom'] = { 0x25BC, 0x0332 },-- BLACK DOWN-POINTING TRIANGLE/COMBINING LOW LINE
  ['CleaningF'] = { 0x24BB },-- CIRCLED LATIN CAPITAL LETTER F
  ['CleaningFF'] = { 0x24BB, 0x0332 },-- CIRCLED LATIN CAPITAL LETTER F/COMBINING LOW LINE
  ['Sun'] = { 0x2609 },-- SUN
  ['Moon'] = { 0x1F319 },-- CRESCENT MOON
  ['Mercury'] = { 0x263F },-- MERCURY
  ['Venus'] = { 0x2640 },-- FEMALE SIGN
  ['Mars'] = { 0x2642 },-- MALE SIGN
  ['Jupiter'] = { 0x2643 },-- JUPITER
  ['Saturn'] = { 0x2644 },-- SATURN
  ['Uranus'] = { 0x2645 },-- URANUS
  ['Neptune'] = { 0x2646 },-- NEPTUNE
  ['Pluto'] = { 0x2647 },-- PLUTO
  ['Earth'] = { 0x2641 },-- EARTH
  ['Bleech'] = { 0x25B3 },-- WHITE UP-POINTING TRIANGLE
  ['NoBleech'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ComputerMouse'] = { 0x1F5B0 },-- TWO BUTTON MOUSE
  ['SerialInterface'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Keyboard'] = { 0x1F5AE },-- WIRED KEYBOARD
  ['SerialPort'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ParallelPort'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Printer'] = { 0x1F5A8 },-- PRINTER
  ['AtNinetyFive'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ShortNinetyfive'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['AtSixty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ShortSixty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ShortFifty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['AtForty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ShortForty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['SpecialForty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['ShortThirty'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['HandWash'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['NoWash'] = { 0xFFFD },-- REPLACEMENT CHARACTER
  ['Recycling'] = { 0x2672 },-- UNIVERSAL RECYCLING SYMBOL
  ['PackingWaste'] = { 0x1F501 },-- CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS
  ['Aries'] = { 0x2648 },-- ARIES
  ['Taurus'] = { 0x2649 },-- TAURUS
  ['Gemini'] = { 0x264A },-- GEMINI
  ['Cancer'] = { 0x264B },-- CANCER
  ['Leo'] = { 0x264C },-- LEO
  ['Virgo'] = { 0x264D },-- VIRGO
  ['Libra'] = { 0x264E },-- LIBRA
  ['Scorpio'] = { 0x264F },-- SCORPIUS
  ['Sagittarius'] = { 0x2650 },-- SAGITTARIUS
  ['Capricorn'] = { 0x2651 },-- CAPRICORN
  ['Aquarius'] = { 0x2652 },-- AQUARIUS
  ['Pisces'] = { 0x2653 },-- PISCES
  ['Valve'] = { 0x29D3 },-- BLACK BOWTIE
  ['Florin'] = { 0x0192 },-- LATIN SMALL LETTER F WITH HOOK
  ['CleaningPP'] = { 0x24C5, 0x0332 },-- CIRCLED LATIN CAPITAL LETTER P/COMBINING LOW LINE
  ['MultiplicationDot'] = { 0x00B7 },-- MIDDLE DOT
  ['Bat'] = { 0x1F987 },-- BAT
  ['WomanFace'] = { 0x1F469 },-- WOMAN
  ['ManFace'] = { 0x1F468 },-- MAN
  }
